/* Bilingual glossary: [topic id, English term, Indonesian term, English definition, Indonesian definition] */
const GLOSSARY = [
  ["states", "particle model", "model partikel", "The idea that all matter is made of tiny moving particles.", "Gagasan bahwa semua materi tersusun dari partikel-partikel kecil yang bergerak."],
  ["states", "melting point", "titik leleh", "The temperature at which a solid turns into a liquid.", "Suhu ketika zat padat berubah menjadi cair."],
  ["states", "boiling point", "titik didih", "The temperature at which a liquid boils; it depends on the pressure.", "Suhu ketika zat cair mendidih; bergantung pada tekanan."],
  ["states", "sublimation", "menyublim", "The change from solid directly to gas.", "Perubahan wujud dari padat langsung menjadi gas."],
  ["mixtures", "element", "unsur", "A substance made of only one kind of atom.", "Zat yang tersusun dari satu jenis atom saja."],
  ["mixtures", "compound", "senyawa", "A substance made of two or more elements chemically joined in a fixed ratio.", "Zat yang tersusun dari dua unsur atau lebih yang terikat secara kimia dengan perbandingan tetap."],
  ["mixtures", "mixture", "campuran", "Two or more substances mixed but not chemically joined.", "Dua zat atau lebih yang tercampur tanpa terikat secara kimia."],
  ["mixtures", "filtration", "penyaringan (filtrasi)", "Separating an insoluble solid from a liquid with filter paper.", "Memisahkan padatan yang tidak larut dari cairan dengan kertas saring."],
  ["mixtures", "distillation", "penyulingan (distilasi)", "Separating liquids by boiling and condensing them.", "Memisahkan cairan dengan cara mendidihkan lalu mengembunkannya."],
  ["mixtures", "chromatography", "kromatografi", "Separating substances by how far they travel through a medium such as paper.", "Memisahkan zat berdasarkan seberapa jauh zat itu bergerak melalui medium seperti kertas."],
  ["atomic-structure", "atomic number", "nomor atom", "The number of protons in the nucleus of an atom.", "Jumlah proton dalam inti atom."],
  ["atomic-structure", "mass number", "nomor massa", "The number of protons plus neutrons in a nucleus.", "Jumlah proton ditambah neutron dalam inti."],
  ["atomic-structure", "isotope", "isotop", "Atoms of the same element with different numbers of neutrons.", "Atom-atom unsur yang sama dengan jumlah neutron berbeda."],
  ["atomic-structure", "ion", "ion", "An atom or group of atoms that has gained or lost electrons.", "Atom atau gugus atom yang telah menerima atau melepas elektron."],
  ["electron-config", "electron configuration", "konfigurasi elektron", "The arrangement of electrons in shells and subshells.", "Susunan elektron dalam kulit dan subkulit."],
  ["electron-config", "orbital", "orbital", "A region around the nucleus where an electron is likely to be found.", "Daerah di sekitar inti tempat elektron paling mungkin ditemukan."],
  ["electron-config", "valence electrons", "elektron valensi", "The electrons in the outer shell, which take part in bonding.", "Elektron di kulit terluar yang berperan dalam ikatan."],
  ["periodic-table", "group", "golongan", "A column of the periodic table; elements in it have similar properties.", "Kolom pada tabel periodik; unsur di dalamnya punya sifat yang mirip."],
  ["periodic-table", "period", "periode", "A row of the periodic table.", "Baris pada tabel periodik."],
  ["periodic-table", "electronegativity", "keelektronegatifan", "How strongly an atom attracts the shared electrons in a bond.", "Seberapa kuat atom menarik pasangan elektron bersama dalam ikatan."],
  ["periodic-table", "ionisation energy", "energi ionisasi", "The energy needed to remove an electron from a gaseous atom.", "Energi yang diperlukan untuk melepas satu elektron dari atom dalam wujud gas."],
  ["ionic-bonding", "ionic bond", "ikatan ion", "The attraction between oppositely charged ions.", "Gaya tarik antara ion-ion yang muatannya berlawanan."],
  ["covalent-bonding", "covalent bond", "ikatan kovalen", "A shared pair of electrons between two atoms.", "Pasangan elektron yang dipakai bersama oleh dua atom."],
  ["covalent-bonding", "lone pair", "pasangan elektron bebas", "A pair of outer electrons not used in bonding.", "Sepasang elektron terluar yang tidak digunakan dalam ikatan."],
  ["molecular-shapes", "VSEPR theory", "teori VSEPR", "Electron pairs around a central atom repel and spread as far apart as possible.", "Pasangan elektron di sekitar atom pusat saling tolak dan menjauh sejauh mungkin."],
  ["molecular-shapes", "polar molecule", "molekul polar", "A molecule with an uneven charge distribution, with a positive and a negative end.", "Molekul dengan sebaran muatan tidak merata, memiliki ujung positif dan negatif."],
  ["forces-structures", "hydrogen bond", "ikatan hidrogen", "A strong attraction between H bonded to N, O or F and a lone pair on another such atom.", "Gaya tarik kuat antara H yang terikat pada N, O, atau F dan pasangan elektron bebas atom sejenis lain."],
  ["forces-structures", "intermolecular forces", "gaya antarmolekul", "Attractions between molecules, weaker than bonds within molecules.", "Gaya tarik antarmolekul, lebih lemah daripada ikatan di dalam molekul."],
  ["chemical-equations", "reactant", "pereaksi (reaktan)", "A substance that reacts at the start of a reaction.", "Zat yang bereaksi di awal reaksi."],
  ["chemical-equations", "product", "hasil reaksi (produk)", "A substance formed in a reaction.", "Zat yang terbentuk dalam reaksi."],
  ["mole-concept", "mole", "mol", "The amount of substance that contains 6.022 × 10²³ particles.", "Jumlah zat yang mengandung 6,022 × 10²³ partikel."],
  ["mole-concept", "molar mass", "massa molar", "The mass of one mole of a substance, in g/mol.", "Massa satu mol zat, dalam g/mol."],
  ["reacting-quantities", "limiting reagent", "pereaksi pembatas", "The reactant that is used up first and so limits the amount of product.", "Pereaksi yang habis lebih dulu sehingga membatasi banyaknya hasil reaksi."],
  ["reacting-quantities", "percentage yield", "persentase hasil", "Actual yield divided by theoretical yield, times 100%.", "Hasil nyata dibagi hasil teoretis, dikali 100%."],
  ["empirical-formula", "empirical formula", "rumus empiris", "The simplest whole-number ratio of atoms in a compound.", "Perbandingan bilangan bulat paling sederhana dari atom-atom dalam senyawa."],
  ["empirical-formula", "molecular formula", "rumus molekul", "The actual number of each kind of atom in a molecule.", "Jumlah sebenarnya setiap jenis atom dalam satu molekul."],
  ["concentration", "concentration", "konsentrasi", "The amount of solute in a given volume of solution, such as mol/L.", "Banyaknya zat terlarut dalam volume larutan tertentu, misalnya mol/L."],
  ["concentration", "solute", "zat terlarut", "The substance that dissolves.", "Zat yang dilarutkan."],
  ["concentration", "solvent", "pelarut", "The liquid that the solute dissolves in.", "Cairan tempat zat terlarut dilarutkan."],
  ["colligative", "colligative property", "sifat koligatif", "A property that depends only on the number of solute particles, not their type.", "Sifat yang hanya bergantung pada jumlah partikel zat terlarut, bukan jenisnya."],
  ["colligative", "osmosis", "osmosis", "Movement of water through a semipermeable membrane into a more concentrated solution.", "Perpindahan air melalui selaput semipermeabel ke larutan yang lebih pekat."],
  ["colloids", "colloid", "koloid", "A mixture with particles between about 1 and 1000 nm that do not settle.", "Campuran dengan partikel berukuran sekitar 1–1000 nm yang tidak mengendap."],
  ["colloids", "Tyndall effect", "efek Tyndall", "The scattering of a light beam by colloid particles.", "Penghamburan berkas cahaya oleh partikel koloid."],
  ["thermochemistry", "enthalpy change (ΔH)", "perubahan entalpi (ΔH)", "The heat taken in or given out by a reaction at constant pressure.", "Kalor yang diserap atau dilepas suatu reaksi pada tekanan tetap."],
  ["thermochemistry", "exothermic", "eksoterm", "A reaction that releases heat to the surroundings (ΔH < 0).", "Reaksi yang melepas kalor ke lingkungan (ΔH < 0)."],
  ["thermochemistry", "endothermic", "endoterm", "A reaction that absorbs heat from the surroundings (ΔH > 0).", "Reaksi yang menyerap kalor dari lingkungan (ΔH > 0)."],
  ["hess-law", "Hess's law", "hukum Hess", "The enthalpy change of a reaction is the same whatever route is taken.", "Perubahan entalpi reaksi selalu sama, apa pun jalur reaksinya."],
  ["reaction-rates", "activation energy", "energi aktivasi", "The minimum energy colliding particles need to react.", "Energi minimum yang diperlukan partikel yang bertumbukan untuk bereaksi."],
  ["reaction-rates", "catalyst", "katalis", "A substance that speeds up a reaction without being used up.", "Zat yang mempercepat reaksi tanpa ikut habis bereaksi."],
  ["rate-laws", "rate constant", "tetapan laju", "The constant k in a rate equation such as rate = k[A]².", "Tetapan k dalam persamaan laju, misalnya laju = k[A]²."],
  ["rate-laws", "order of reaction", "orde reaksi", "The power to which a concentration is raised in the rate equation.", "Pangkat konsentrasi dalam persamaan laju."],
  ["equilibrium", "dynamic equilibrium", "kesetimbangan dinamis", "A state where forward and reverse reactions go at the same rate.", "Keadaan ketika reaksi maju dan reaksi balik berlangsung dengan laju yang sama."],
  ["equilibrium", "Le Chatelier's principle", "asas Le Chatelier", "A system at equilibrium shifts to oppose a change imposed on it.", "Sistem setimbang bergeser untuk melawan perubahan yang diberikan padanya."],
  ["acids-bases-intro", "acid", "asam", "A substance that releases H⁺ ions in water (pH below 7).", "Zat yang melepas ion H⁺ dalam air (pH di bawah 7)."],
  ["acids-bases-intro", "base", "basa", "A substance that accepts H⁺ or releases OH⁻ in water (pH above 7).", "Zat yang menerima H⁺ atau melepas OH⁻ dalam air (pH di atas 7)."],
  ["acids-bases-intro", "indicator", "indikator", "A substance whose colour depends on pH.", "Zat yang warnanya bergantung pada pH."],
  ["acids-bases-intro", "neutralisation", "penetralan (netralisasi)", "The reaction of an acid with a base to give a salt and water.", "Reaksi asam dengan basa yang menghasilkan garam dan air."],
  ["acid-base-theories", "conjugate base", "basa konjugasi", "What is left when an acid has given away H⁺.", "Spesi yang tersisa setelah asam melepas H⁺."],
  ["acid-base-theories", "weak acid", "asam lemah", "An acid that ionises only partly in water.", "Asam yang hanya terionisasi sebagian dalam air."],
  ["ph-calculations", "pH", "pH", "Minus the logarithm of the hydrogen-ion concentration: pH = −log[H⁺].", "Negatif logaritma konsentrasi ion hidrogen: pH = −log[H⁺]."],
  ["titration", "titration", "titrasi", "Adding a solution of known concentration to find the concentration of another.", "Menambahkan larutan yang konsentrasinya diketahui untuk menentukan konsentrasi larutan lain."],
  ["titration", "equivalence point", "titik ekuivalen", "The point where the acid and base have reacted exactly.", "Titik ketika asam dan basa tepat habis bereaksi."],
  ["buffers-salts", "buffer solution", "larutan penyangga", "A solution that resists changes in pH when small amounts of acid or base are added.", "Larutan yang mempertahankan pH ketika ditambah sedikit asam atau basa."],
  ["buffers-salts", "hydrolysis", "hidrolisis", "The reaction of an ion with water that changes the pH.", "Reaksi ion dengan air yang mengubah pH."],
  ["solubility-product", "solubility product (Ksp)", "hasil kali kelarutan (Ksp)", "The product of ion concentrations in a saturated solution of a sparingly soluble salt.", "Hasil kali konsentrasi ion dalam larutan jenuh garam yang sukar larut."],
  ["redox-basics", "oxidation", "oksidasi", "Loss of electrons, or an increase in oxidation number.", "Pelepasan elektron, atau kenaikan bilangan oksidasi."],
  ["redox-basics", "reduction", "reduksi", "Gain of electrons, or a decrease in oxidation number.", "Penerimaan elektron, atau penurunan bilangan oksidasi."],
  ["redox-basics", "oxidation number", "bilangan oksidasi", "The charge an atom would have if all its bonds were ionic.", "Muatan yang dimiliki atom seandainya semua ikatannya ion."],
  ["galvanic-cells", "anode", "anode", "The electrode where oxidation happens.", "Elektrode tempat terjadi oksidasi."],
  ["galvanic-cells", "cathode", "katode", "The electrode where reduction happens.", "Elektrode tempat terjadi reduksi."],
  ["galvanic-cells", "standard electrode potential", "potensial elektrode standar", "The voltage of a half-cell measured against the hydrogen electrode.", "Tegangan setengah sel yang diukur terhadap elektrode hidrogen."],
  ["electrolysis", "electrolysis", "elektrolisis", "Breaking down a compound using electricity.", "Penguraian senyawa dengan menggunakan listrik."],
  ["corrosion", "corrosion", "korosi", "The slow destruction of a metal by reaction with its surroundings, such as rusting.", "Perusakan logam secara perlahan akibat bereaksi dengan lingkungannya, misalnya perkaratan."],
  ["hydrocarbons", "hydrocarbon", "hidrokarbon", "A compound of hydrogen and carbon only.", "Senyawa yang hanya tersusun dari hidrogen dan karbon."],
  ["hydrocarbons", "alkane", "alkana", "A saturated hydrocarbon with only single C–C bonds.", "Hidrokarbon jenuh yang hanya memiliki ikatan tunggal C–C."],
  ["hydrocarbons", "alkene", "alkena", "A hydrocarbon with a C=C double bond.", "Hidrokarbon yang memiliki ikatan rangkap dua C=C."],
  ["functional-groups", "functional group", "gugus fungsi", "The group of atoms that gives an organic compound its typical reactions.", "Gugus atom yang menentukan reaksi khas suatu senyawa organik."],
  ["isomerism", "isomers", "isomer", "Compounds with the same molecular formula but different structures.", "Senyawa-senyawa dengan rumus molekul sama tetapi strukturnya berbeda."],
  ["organic-reactions", "esterification", "esterifikasi", "The reaction of an alcohol with a carboxylic acid to form an ester and water.", "Reaksi alkohol dengan asam karboksilat yang menghasilkan ester dan air."],
  ["benzene", "aromatic compound", "senyawa aromatik", "A compound containing a benzene ring.", "Senyawa yang mengandung cincin benzena."],
  ["polymers", "polymer", "polimer", "A very long molecule made of many repeating units (monomers).", "Molekul sangat panjang yang tersusun dari banyak satuan berulang (monomer)."],
  ["biomolecules", "protein", "protein", "A polymer of amino acids joined by peptide bonds.", "Polimer asam amino yang dihubungkan oleh ikatan peptida."],
  ["biomolecules", "carbohydrate", "karbohidrat", "A compound of C, H and O such as sugars and starch.", "Senyawa C, H, dan O seperti gula dan pati."],
  ["group-chemistry", "alkali metals", "logam alkali", "The very reactive metals of Group 1, such as sodium and potassium.", "Logam yang sangat reaktif di golongan 1, misalnya natrium dan kalium."],
  ["group-chemistry", "halogens", "halogen", "The reactive non-metals of Group 17, such as chlorine.", "Nonlogam reaktif di golongan 17, misalnya klorin."],
  ["group-chemistry", "noble gases", "gas mulia", "The very unreactive elements of Group 18.", "Unsur-unsur yang sangat tidak reaktif di golongan 18."],
  ["transition-metals", "transition metal", "logam transisi", "A d-block metal that forms coloured ions and variable oxidation states.", "Logam blok d yang membentuk ion berwarna dan bilangan oksidasi beragam."],
  ["transition-metals", "complex ion", "ion kompleks", "A metal ion surrounded by ligands bonded to it.", "Ion logam yang dikelilingi ligan yang terikat padanya."],
  ["metals-extraction", "ore", "bijih", "A rock from which a metal can be extracted profitably.", "Batuan yang dapat diolah untuk diambil logamnya secara menguntungkan."],
  ["nuclear-chemistry", "radioactive decay", "peluruhan radioaktif", "The spontaneous change of an unstable nucleus, giving off radiation.", "Perubahan spontan inti yang tidak stabil dengan memancarkan radiasi."],
  ["environmental-chemistry", "greenhouse effect", "efek rumah kaca", "The warming of the Earth because gases such as CO₂ absorb infrared radiation.", "Pemanasan Bumi karena gas seperti CO₂ menyerap radiasi inframerah."],
  ["chemical-thermodynamics", "Gibbs free energy", "energi bebas Gibbs", "G = H − TS; a reaction is spontaneous when ΔG is negative.", "G = H − TS; reaksi berlangsung spontan jika ΔG negatif."],
  ["spectroscopy", "spectroscopy", "spektroskopi", "Studying substances by how they absorb or emit radiation.", "Mempelajari zat berdasarkan cara zat itu menyerap atau memancarkan radiasi."]
];
