/* ==========================================================================
   TRACK G — Acids, Bases & Salts
   ========================================================================== */
(() => {
const lg = x => Math.log10(x);
const pH2 = x => sig(x, 3);
const EVERYDAY = () => [[0.5, T`battery acid`], [1.5, T`stomach acid`], [2.2, T`lemon juice`], [2.9, T`vinegar`], [5, T`coffee`], [5.6, T`clean rain`], [6.6, T`milk`], [7, T`pure water`], [7.4, T`blood`], [8.1, T`sea water`], [8.3, T`baking soda`], [10, T`soap`], [11.5, T`ammonia`], [12.5, T`bleach`], [13.5, T`drain cleaner`]];
const WEAK = [['CH3COOH', 'CH3COO-', 1.8e-5, 'ethanoic (acetic) acid'], ['HCOOH', 'HCOO-', 1.8e-4, 'methanoic (formic) acid'], ['HF', 'F-', 6.8e-4, 'hydrofluoric acid'], ['HNO2', 'NO2-', 4.5e-4, 'nitrous acid'], ['HCN', 'CN-', 6.2e-10, 'hydrocyanic acid']];
const acName = n => ({ 'ethanoic (acetic) acid': T`ethanoic (acetic) acid`, 'methanoic (formic) acid': T`methanoic (formic) acid`, 'hydrofluoric acid': T`hydrofluoric acid`, 'nitrous acid': T`nitrous acid`, 'hydrocyanic acid': T`hydrocyanic acid` })[n];
const KSP = [['AgCl', 'Ag+', 'Cl-', 1, 1, 1.8e-10], ['BaSO4', 'Ba^2+', 'SO4^2-', 1, 1, 1.1e-10], ['AgBr', 'Ag+', 'Br-', 1, 1, 5.0e-13], ['CaF2', 'Ca^2+', 'F-', 1, 2, 3.9e-11], ['PbI2', 'Pb^2+', 'I-', 1, 2, 7.1e-9], ['Mg(OH)2', 'Mg^2+', 'OH-', 1, 2, 5.6e-12], ['Ag2CrO4', 'Ag+', 'CrO4^2-', 2, 1, 1.1e-12], ['CaCO3', 'Ca^2+', 'CO3^2-', 1, 1, 3.4e-9]];
level({
  id: 'acids', mark: 'G', name: 'Acids, Bases & Salts', short: 'Acids & bases', band: 'pH · theories · titration · buffers · Ksp', color: 'lv7',
  blurb: 'Acids, bases and indicators, the pH scale, the Arrhenius, Brønsted–Lowry and Lewis theories, calculating pH, titrations and titration curves, buffers, salt hydrolysis and solubility products.',
  topics: [
{
  id: 'acids-bases-intro', stage: 'jh', title: 'Acids, Bases, Indicators & pH',
  blurb: 'Properties of acids and bases, alkalis, indicators, the pH scale and everyday examples, neutralisation, and the reactions of acids with metals, carbonates and bases.',
  lesson: () => T`
<p><b>Acids</b> taste sour (lemon juice, vinegar), turn blue litmus red and react with metals and carbonates.<br><b>Bases</b> are their chemical opposites; bases that dissolve in water are called <b>alkalis</b>: they feel soapy and turn red litmus blue. In water, acids produce hydrogen ions $\ce{H+}$ and alkalis produce hydroxide ions $\ce{OH-}$.</p>
${FigW(phScaleSvg(EVERYDAY(), { names: [T`← more acidic`, T`neutral`, T`more alkaline →`], label: T`The pH scale from 0 to 14 in universal indicator colours with everyday examples from battery acid to drain cleaner` }), T`The pH scale with universal-indicator colours and typical values (US EPA and USGS). Each step of 1 pH unit is a tenfold change in $\ce{H+}$ concentration: lemon juice (pH 2) has 1000 times more $\ce{H+}$ than coffee (pH 5).`)}
${Tbl([T`Indicator`, T`In acid`, T`In alkali`], [[T`litmus`, T`red`, T`blue`], [T`phenolphthalein`, T`colourless`, T`pink`], [T`methyl orange`, T`red`, T`yellow`], [T`universal indicator`, T`red → orange → yellow`, T`blue → violet`], [T`red cabbage or turmeric extract`, T`red / yellow`, T`green / red-brown`]])}
${Key(T`<p><b>Neutralisation:</b> acid + base → salt + water. The ionic equation is always $\ce{H+(aq) + OH-(aq) -> H2O(l)}$. Other acid reactions:</p><p>acid + metal → salt + hydrogen: $\ce{Zn + 2HCl -> ZnCl2 + H2}$<br>acid + carbonate → salt + water + carbon dioxide: $\ce{CaCO3 + 2HCl -> CaCl2 + H2O + CO2}$<br>acid + metal oxide → salt + water: $\ce{CuO + H2SO4 -> CuSO4 + H2O}$</p>`)}
${Tbl([T`Acid`, T`Formula`, T`Salts are called`], [[T`hydrochloric acid`, '$\\ce{HCl}$', T`chlorides`], [T`sulfuric acid`, '$\\ce{H2SO4}$', T`sulfates`], [T`nitric acid`, '$\\ce{HNO3}$', T`nitrates`], [T`ethanoic acid`, '$\\ce{CH3COOH}$', T`ethanoates`]])}
${Tip(T`<p>Test for hydrogen: a lit splint gives a squeaky pop. Test for carbon dioxide: it turns limewater milky. Everyday neutralisation: antacid tablets for stomach acid, lime ($\ce{CaO}$) for acidic soil, toothpaste against acids made by bacteria.</p>`)}`,
  gens: [
    () => { const [p, t] = pick(EVERYDAY()), a = p < 6.5 ? T`acidic` : p > 7.5 ? T`alkaline` : T`neutral`; return { q: T`${t} has a pH of about ${NUM(p)}. Is it acidic, neutral or alkaline?`, a, w: [T`acidic`, T`neutral`, T`alkaline`].filter(x => x !== a), only: 'mc', s: T`Below 7 acidic, 7 neutral, above 7 alkaline: <b>${a}</b>.` }; },
    () => { const p1 = ri(1, 6), p2 = p1 + ri(1, 3), f = 10 ** (p2 - p1); return { q: T`How many times more $\ce{H+}$ ions does a solution of pH ${p1} have than one of pH ${p2}?`, a: f, w: [p2 - p1, 2 * (p2 - p1), f / 10 === 1 ? 100 : f / 10], s: T`Each pH unit is a factor of 10: $10^{${p2 - p1}} = ${f}$.` }; },
    () => { const [ind, env, c] = pick([[T`phenolphthalein`, T`an alkali`, T`pink`], [T`phenolphthalein`, T`an acid`, T`colourless`], [T`litmus`, T`an acid`, T`red`], [T`litmus`, T`an alkali`, T`blue`], [T`methyl orange`, T`an acid`, T`red`], [T`methyl orange`, T`an alkali`, T`yellow`]]); return { q: T`What colour is ${ind} in ${env}?`, a: c, w: [T`pink`, T`colourless`, T`red`, T`blue`, T`yellow`].filter(x => x !== c).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`<b>${c}</b>.` }; },
    () => { const [r, p] = pick([[T`zinc + sulfuric acid`, T`zinc sulfate + hydrogen`], [T`magnesium + hydrochloric acid`, T`magnesium chloride + hydrogen`], [T`calcium carbonate + hydrochloric acid`, T`calcium chloride + water + carbon dioxide`], [T`sodium hydroxide + nitric acid`, T`sodium nitrate + water`], [T`copper(II) oxide + sulfuric acid`, T`copper(II) sulfate + water`], [T`potassium hydroxide + hydrochloric acid`, T`potassium chloride + water`]]), all = [T`zinc sulfate + hydrogen`, T`magnesium chloride + hydrogen`, T`calcium chloride + water + carbon dioxide`, T`sodium nitrate + water`, T`copper(II) sulfate + water`, T`potassium chloride + water`]; return { q: T`What are the products of ${r}?`, a: p, w: all.filter(x => x !== p).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`<b>${p}</b>.` }; },
    () => pick([
      { q: T`Which ion do all acids produce in water?`, a: '$\\ce{H+}$', w: ['$\\ce{OH-}$', '$\\ce{Cl-}$', '$\\ce{Na+}$'], only: 'mc', s: T`Hydrogen ions, $\ce{H+}$ (in water $\ce{H3O+}$).` },
      { q: T`What is the ionic equation for every neutralisation of an acid by an alkali?`, a: '$\\ce{H+ + OH- -> H2O}$', w: ['$\\ce{Na+ + Cl- -> NaCl}$', '$\\ce{2H+ -> H2}$', '$\\ce{H2O -> H+ + OH-}$'], only: 'mc', s: T`The other ions are spectator ions.` },
      { q: T`Which gas turns limewater milky?`, a: T`carbon dioxide`, w: [T`hydrogen`, T`oxygen`, T`chlorine`], only: 'mc', s: T`$\ce{CO2}$ forms a white precipitate of $\ce{CaCO3}$.` },
    ]),
  ],
},
{
  id: 'acid-base-theories', stage: 'sh', title: 'Acid–Base Theories & Strength',
  blurb: 'Arrhenius, Brønsted–Lowry and Lewis definitions, conjugate acid–base pairs, amphoteric substances, strong and weak acids and bases, and the acid dissociation constant Ka.',
  lesson: () => T`
<p>Three definitions, each wider than the last:</p>
${Tbl([T`Theory`, T`Acid`, T`Base`, T`Example`], [[T`Arrhenius (1884)`, T`gives $\ce{H+}$ in water`, T`gives $\ce{OH-}$ in water`, '$\\ce{HCl}$, $\\ce{NaOH}$'], [T`Brønsted–Lowry (1923)`, T`proton ($\ce{H+}$) donor`, T`proton acceptor`, '$\\ce{NH3 + H2O <=> NH4+ + OH-}$'], [T`Lewis (1923)`, T`electron-pair acceptor`, T`electron-pair donor`, '$\\ce{BF3 + NH3 -> F3B-NH3}$']])}
${Key(T`<p>In a Brønsted–Lowry reaction the acid gives $\ce{H+}$ to the base. What remains of the acid is its <b>conjugate base</b>; the base becomes its <b>conjugate acid</b>: $$\underset{\text{acid}}{\ce{HCl}} + \underset{\text{base}}{\ce{H2O}} \ce{->} \underset{\text{conj. acid}}{\ce{H3O+}} + \underset{\text{conj. base}}{\ce{Cl-}}$$ Conjugate pairs differ by exactly one $\ce{H+}$. Water can act as an acid or a base: it is <b>amphoteric</b>.</p>`)}
<h3>Strong and weak</h3>
${Fig(dissociationSvg({ names: [T`strong acid: fully ionised`, T`weak acid: mostly molecules`], label: T`A strong acid is completely split into hydrogen ions and anions; a weak acid is mostly undissociated molecules with only a few ions` }), T`A <b>strong</b> acid ($\ce{HCl}$, $\ce{HNO3}$, $\ce{H2SO4}$) ionises completely in water. A <b>weak</b> acid ($\ce{CH3COOH}$, citric acid, carbonic acid) ionises only partly: an equilibrium $\ce{HA <=> H+ + A-}$ lies far to the left. For ethanoic acid only about 1% of molecules are ionised at 0.1 M.`)}
${Key(T`<p>The strength of a weak acid is measured by the <b>acid dissociation constant</b>: $$K_a = \frac{[\ce{H+}][\ce{A-}]}{[\ce{HA}]} \qquad pK_a = -\log K_a$$ The larger $K_a$ (the smaller $pK_a$), the stronger the acid. Ethanoic acid: $K_a = 1.8 \times 10^{-5}$, $pK_a = 4.74$. Similarly $K_b$ for weak bases such as ammonia ($K_b = 1.8 \times 10^{-5}$).</p>`)}
${Tip(T`<p>Strong ≠ concentrated. "Strong" means fully ionised; "concentrated" means a lot of acid per litre. A dilute solution of a strong acid can have the same pH as a concentrated weak acid.</p>`)}`,
  gens: [
    () => { const [e, a] = pick([['\\ce{HCl + H2O -> H3O+ + Cl-}', ['HCl', 'H2O', 'H3O+', 'Cl-']], ['\\ce{NH3 + H2O <=> NH4+ + OH-}', ['H2O', 'NH3', 'NH4+', 'OH-']], ['\\ce{CH3COOH + H2O <=> H3O+ + CH3COO-}', ['CH3COOH', 'H2O', 'H3O+', 'CH3COO-']], ['\\ce{HCO3- + OH- <=> CO3^2- + H2O}', ['HCO3-', 'OH-', 'H2O', 'CO3^2-']], ['\\ce{NH4+ + OH- <=> NH3 + H2O}', ['NH4+', 'OH-', 'H2O', 'NH3']]]), role = ri(0, 3), N = [T`the Brønsted–Lowry acid`, T`the Brønsted–Lowry base`, T`the conjugate acid`, T`the conjugate base`]; return { q: T`In $${e}$, which species is ${N[role]}?`, a: `$\\ce{${a[role]}}$`, w: a.filter((_, i) => i !== role).map(x => `$\\ce{${x}}$`), only: 'mc', s: T`Acid ${`$\\ce{${a[0]}}$`} gives $\ce{H+}$ to base ${`$\\ce{${a[1]}}$`}; they become ${`$\\ce{${a[2]}}$`} (conjugate acid) and ${`$\\ce{${a[3]}}$`} (conjugate base).` }; },
    () => { const [x, c] = pick([['HCl', 'Cl-'], ['H2SO4', 'HSO4-'], ['NH4+', 'NH3'], ['H2O', 'OH-'], ['HCO3-', 'CO3^2-'], ['CH3COOH', 'CH3COO-'], ['H3O+', 'H2O'], ['HNO3', 'NO3-']]), wr = [c.replace(/-$/, '').replace(/\^2-$/, '') || 'X', x + '+', x.replace('H', 'H2')]; return { q: T`What is the conjugate base of $\ce{${x}}$?`, a: `$\\ce{${c}}$`, w: [...new Set(wr)].filter(w => w !== c).map(w => `$\\ce{${w}}$`), only: 'mc', s: T`Remove one $\ce{H+}$: $\ce{${c}}$.` }; },
    () => { const [x, t] = pick([['HCl', 0], ['HNO3', 0], ['H2SO4', 0], ['HBr', 0], ['CH3COOH', 1], ['HF', 1], ['H2CO3', 1], ['HCOOH', 1], ['NaOH', 2], ['KOH', 2], ['NH3', 3], ['Ca(OH)2', 2]]), N = [T`strong acid`, T`weak acid`, T`strong base`, T`weak base`]; return { q: T`Classify $\ce{${x}}$.`, a: N[t], w: N.filter((_, i) => i !== t), only: 'mc', s: T`$\ce{${x}}$ is a <b>${N[t]}</b>.` }; },
    () => { const sel = [...WEAK].sort(() => rng() - 0.5).slice(0, 3), best = sel.reduce((a, b) => (b[2] > a[2] ? b : a)); return { q: T`Which is the strongest acid? ${sel.map(w => `${acName(w[3])} ($K_a = ${sciT(w[2], 2)}$)`).join('; ')}`, a: acName(best[3]), w: sel.filter(w => w !== best).map(w => acName(w[3])), only: 'mc', s: T`The largest $K_a$ is the strongest acid: <b>${acName(best[3])}</b>.` }; },
    () => { const Ka = pick([1.8e-5, 6.8e-4, 4.5e-4, 1e-3, 1e-7, 6.2e-10]), pk = sig(-lg(Ka), 3); return { q: T`$K_a = ${sciT(Ka, 2)}$. What is the $pK_a$?`, a: pk, rtol: 0.005, w: [sig(lg(Ka), 3), sig(-Math.log(Ka), 3), sig(pk / 2, 3)], s: T`$pK_a = -\log(${sciT(Ka, 2)}) = ${M(pk)}$.` }; },
    () => pick([
      { q: T`What is a Lewis acid?`, a: T`An electron-pair acceptor`, w: [T`An electron-pair donor`, T`A proton acceptor`, T`A substance that gives OH⁻ in water`], only: 'mc', s: T`e.g. $\ce{BF3}$ accepts the lone pair of $\ce{NH3}$.` },
      { q: T`Why is water called amphoteric?`, a: T`It can act as an acid and as a base`, w: [T`It is neutral`, T`It conducts electricity`, T`It dissolves both acids and bases`], only: 'mc', s: T`It donates $\ce{H+}$ to $\ce{NH3}$ and accepts $\ce{H+}$ from $\ce{HCl}$.` },
    ]),
  ],
},
{
  id: 'ph-calculations', stage: 'sh', title: 'Calculating pH',
  blurb: 'The ionic product of water Kw, pH and pOH, the pH of strong acids and bases, and the pH of weak acids and bases from Ka and Kb.',
  lesson: () => T`
${Key(T`<p>$$\mathrm{pH} = -\log[\ce{H+}] \qquad [\ce{H+}] = 10^{-\mathrm{pH}}$$ Water ionises very slightly: $\ce{H2O <=> H+ + OH-}$ with $$K_w = [\ce{H+}][\ce{OH-}] = 1.0 \times 10^{-14} \text{ at } 25\ °\mathrm{C}$$ so $\mathrm{pH} + \mathrm{pOH} = 14$. In pure water $[\ce{H+}] = [\ce{OH-}] = 10^{-7}$ M and pH = 7.</p>`)}
${Fig(planeSvg({ W: 420, H: 250, x: [0, 14.5], y: [0, 14.5], step: [1, 1], tickX: 2, tickY: 2, xl: 'pH', yl: T`−log c`, fns: [{ f: p => p, from: 0, to: 14, cls: 'mf-c4', label: '[H⁺]', at: 11.5, dx: 6, dy: 14 }, { f: p => 14 - p, from: 0, to: 14, cls: 'mf-c1', label: '[OH⁻]', at: 11.5, dx: 6, dy: -4 }], segs: [[7, 0, 7, 7, 'mf-grid', true]], pts: [[7, 7, T`neutral`, 'start']], label: T`As pH rises, the hydrogen ion concentration falls and the hydroxide concentration rises; they are equal at pH 7` }), T`$-\log[\ce{H+}]$ and $-\log[\ce{OH-}]$ against pH: the lines cross at pH 7, where both are $10^{-7}$ M. Their sum is always 14.`)}
<h3>Strong acids and bases</h3>
<p>They ionise completely, so for a monoprotic strong acid $[\ce{H+}] = c$: 0.01 M HCl has pH $= -\log 0.01 = 2$. For a strong base, find $[\ce{OH-}]$, then pOH, then pH $= 14 - \mathrm{pOH}$: 0.01 M NaOH has pOH 2, pH 12. For $\ce{Ba(OH)2}$ or $\ce{H2SO4}$ count 2 per formula.</p>
<h3>Weak acids and bases</h3>
${Key(T`<p>Only a small fraction ionises, so $[\ce{HA}] \approx c$ and $$[\ce{H+}] = \sqrt{K_a \cdot c} \qquad [\ce{OH-}] = \sqrt{K_b \cdot c}$$ The degree of ionisation is $\alpha = \sqrt{K_a / c}$.</p>`)}
${Ex(T`<p>pH of 0.10 M ethanoic acid ($K_a = 1.8 \times 10^{-5}$): $[\ce{H+}] = \sqrt{1.8 \times 10^{-6}} = 1.34 \times 10^{-3}$ M, pH = 2.87. Compare 0.10 M HCl: pH 1.</p>`)}
${Tip(T`<p>On a calculator: pH = −log(c); $[\ce{H+}]$ = 10^(−pH). A pH to 2 decimal places matches a concentration to 2 significant figures.</p>`)}`,
  gens: [
    () => { const e = ri(1, 5), m = pick([1, 2, 5, 3]), c = m * 10 ** -e, p = sig(-lg(c), 3); return { q: T`What is the pH of ${NUM(sig(c, 3))} M HCl?`, a: p, rtol: 0.005, w: [sig(14 - p, 3), sig(-Math.log(c), 3), e], s: T`$\mathrm{pH} = -\log(${M(sig(c, 3))}) = ${M(p)}$.` }; },
    () => { const [b, n] = pick([['NaOH', 1], ['KOH', 1], ['Ba(OH)2', 2], ['Ca(OH)2', 2]]), c = pick([0.1, 0.01, 0.05, 0.001, 0.02]), oh = c * n, p = sig(14 + lg(oh), 3); return { q: T`What is the pH of ${NUM(c)} M $\ce{${b}}$?`, a: p, rtol: 0.005, w: [sig(-lg(oh), 3), sig(14 + lg(c), 3) === p ? sig(p - 1, 3) : sig(14 + lg(c), 3), sig(14 - lg(oh), 3)], s: T`$[\ce{OH-}] = ${n > 1 ? n + ' \times ' : ''}${M(c)} = ${M(sig(oh, 3))}$ M; pOH $= ${M(sig(-lg(oh), 3))}$; pH $= 14 - ${M(sig(-lg(oh), 3))} = ${M(p)}$.` }; },
    () => { const p = pick([2, 3, 4.5, 5, 9, 11, 12.3, 1.7]), h = 10 ** -p; return { q: T`A solution has pH ${NUM(p)}. What is $[\ce{H+}]$?`, a: `$${sciT(sig(h, 2), 2)}$ M`, w: [`$${sciT(sig(10 ** -(14 - p), 2), 2)}$ M`, `$${sciT(sig(10 ** p / 1e14, 2), 2)}$ M` === `$${sciT(sig(h, 2), 2)}$ M` ? `$${sciT(sig(h * 10, 2), 2)}$ M` : `$${sciT(sig(p / 100, 2), 2)}$ M`, `$${sciT(sig(h * 10, 2), 2)}$ M`], only: 'mc', s: T`$[\ce{H+}] = 10^{-${M(p)}} = ${sciT(sig(h, 2), 2)}$ M.` }; },
    () => { const w = pick(WEAK.slice(0, 4)), c = pick([0.1, 0.01, 0.2, 0.05]), h = Math.sqrt(w[2] * c), p = sig(-lg(h), 3); return { q: T`Find the pH of ${NUM(c)} M ${acName(w[3])} ($K_a = ${sciT(w[2], 2)}$).`, a: p, rtol: 0.01, w: [sig(-lg(c), 3), sig(-lg(w[2] * c), 3), sig(14 - p, 3)], s: T`$[\ce{H+}] = \sqrt{${sciT(w[2], 2)} \times ${M(c)}} = ${sciT(sig(h, 3))}$ M; pH $= ${M(p)}$.` }; },
    () => { const c = pick([0.1, 0.2, 0.05, 0.01]), Kb = 1.8e-5, oh = Math.sqrt(Kb * c), p = sig(14 + lg(oh), 3); return { q: T`Find the pH of ${NUM(c)} M ammonia ($K_b = 1.8 \times 10^{-5}$).`, a: p, rtol: 0.01, w: [sig(-lg(oh), 3), sig(14 + lg(c), 3), sig(-lg(c), 3)], s: T`$[\ce{OH-}] = \sqrt{1.8 \times 10^{-5} \times ${M(c)}} = ${sciT(sig(oh, 3))}$ M; pOH $= ${M(sig(-lg(oh), 3))}$; pH $= ${M(p)}$.` }; },
    () => { const p = pick([3, 4, 5.5, 9, 10.5, 12]), po = sig(14 - p, 3); return { q: T`A solution has pH ${NUM(p)}. What is its pOH?`, a: po, w: [p, sig(7 - p, 3), sig(po + 1, 3)], s: T`pOH $= 14 - ${M(p)} = ${M(po)}$.` }; },
  ],
},
{
  id: 'titration', stage: 'sh', title: 'Acid–Base Titration',
  blurb: 'Titration technique, the equivalence point and end point, choosing an indicator, titration curves for strong and weak acids, and titration calculations.',
  lesson: () => T`
<p>A <b>titration</b> finds the unknown concentration of a solution by reacting it exactly with a standard solution. A pipette measures a fixed volume of one solution into a conical flask with a few drops of indicator; the other solution is added from a burette until the indicator just changes colour.</p>
${Fig(titrationSetupSvg({ names: [T`burette (titrant)`, T`tap`, T`conical flask + indicator`, T`white tile`], label: T`Titration set-up: a burette clamped above a conical flask standing on a white tile` }), T`Titration set-up. Read the burette at the bottom of the meniscus, swirl the flask, and add the titrant drop by drop near the end point. Repeat until two titres agree within 0.10 mL.`)}
${Key(T`<p>At the <b>equivalence point</b> the acid and base have reacted in exactly the ratio of the equation. The <b>end point</b> is where the indicator changes colour; a good indicator changes colour at (close to) the equivalence point. $$n = c \times V \qquad \frac{c_aV_a}{a} = \frac{c_bV_b}{b}$$ for $a$ acid + $b$ base in the equation.</p>`)}
${FigRow([[titrationSvg({ W: 300, H: 250, bands: [[8.2, 10, 'mf-f2', T`phenolphthalein`], [3.1, 4.4, 'mf-f1', T`methyl orange`]], names: { x: T`V NaOH (mL)`, eq: T`equivalence` }, label: T`Titration curve of hydrochloric acid with sodium hydroxide: a steep rise from pH 3 to 11 at 25 millilitres` }), T`strong acid + strong base: equivalence at pH 7`], [titrationSvg({ W: 300, H: 250, Ka: 1.8e-5, bands: [[8.2, 10, 'mf-f2', T`phenolphthalein`], [3.1, 4.4, 'mf-f1', T`methyl orange`]], names: { x: T`V NaOH (mL)`, eq: T`equivalence` }, label: T`Titration curve of ethanoic acid with sodium hydroxide: starts at pH 2.9, equivalence near pH 8.7` }), T`weak acid + strong base: equivalence at pH 8.7`]], T`Curves calculated for 25.0 mL of 0.100 M acid titrated with 0.100 M NaOH. For the strong acid both indicators change within the vertical part. For ethanoic acid the jump is shorter and above 7, so only phenolphthalein works. At half-equivalence (12.5 mL) pH = $pK_a$ = 4.74.`)}
${Ex(T`<p>25.0 mL of NaOH needs 20.0 mL of 0.100 M $\ce{H2SO4}$. $n(\ce{H2SO4}) = 0.100 \times 0.0200 = 2.00 \times 10^{-3}$ mol; $\ce{H2SO4 + 2NaOH -> Na2SO4 + 2H2O}$, so $n(\ce{NaOH}) = 4.00 \times 10^{-3}$ mol and $c = \frac{4.00 \times 10^{-3}}{0.0250} = 0.160$ M.</p>`)}
${Tip(T`<p>Rinse the burette with the titrant and the pipette with the solution it will measure, but rinse the conical flask with distilled water only: water in the flask does not change the number of moles in it.</p>`)}`,
  gens: [
    () => { const ca = pick([0.1, 0.2, 0.05, 0.15]), Va = pick([20, 25, 10]), Vb = pick([12.5, 15, 20, 22.4, 18.6, 25]), cb = sig(ca * Va / Vb, 3); return { q: T`${Q(Va, 'mL')} of ${NUM(ca)} M HCl is neutralised by ${Q(Vb, 'mL')} of NaOH. What is the concentration of the NaOH (in M)?`, a: cb, u: 'M', rtol: 0.01, w: [sig(ca * Vb / Va, 3), sig(ca * Va * Vb / 1000, 3), sig(cb * 2, 3)], s: T`1 : 1, so $c_b = \frac{${M(ca)} \times ${M(Va)}}{${M(Vb)}} = ${M(cb)}$ M.` }; },
    () => { const ca = pick([0.1, 0.05, 0.2]), Va = pick([10, 20, 25]), Vb = pick([15, 20, 25, 30, 40]), cb = sig(2 * ca * Va / Vb, 3); return { q: T`${Q(Va, 'mL')} of ${NUM(ca)} M $\ce{H2SO4}$ is neutralised by ${Q(Vb, 'mL')} of NaOH ($\ce{H2SO4 + 2NaOH -> Na2SO4 + 2H2O}$). What is the concentration of the NaOH (in M)?`, a: cb, u: 'M', rtol: 0.01, w: [sig(ca * Va / Vb, 3), sig(ca * Va / Vb / 2, 3), sig(cb * 2, 3)], s: T`$n(\ce{H2SO4}) = ${M(sig(ca * Va / 1000, 3))}$ mol; ×2 for NaOH $= ${M(sig(2 * ca * Va / 1000, 3))}$ mol; $c = ${M(cb)}$ M.` }; },
    () => { const [t, a] = pick([[T`a strong acid with a strong base`, T`phenolphthalein or methyl orange`], [T`a weak acid with a strong base`, T`phenolphthalein`], [T`a strong acid with a weak base`, T`methyl orange`]]); return { q: T`Which indicator is suitable for titrating ${t}?`, a, w: [T`phenolphthalein or methyl orange`, T`phenolphthalein`, T`methyl orange`, T`no indicator works`].filter(x => x !== a), only: 'mc', s: T`The indicator must change colour within the steep part of the curve: <b>${a}</b>.` }; },
    () => { const [t, p] = pick([[T`HCl with NaOH`, 7], [T`CH₃COOH with NaOH`, 8.7], [T`HCl with NH₃`, 5.3]]); return { q: T`Approximately what is the pH at the equivalence point when titrating ${t} (0.1 M each)?`, a: `${NUM(p)}`, w: ['7', '8.7', '5.3', '1', '13'].filter(x => x !== String(p) && x !== M(p)).slice(0, 3), only: 'mc', s: T`Strong + strong gives a neutral salt (pH 7); a weak acid gives a basic salt (above 7); a weak base gives an acidic salt (below 7).` }; },
    () => { const pk = pick([4.74, 3.75, 4.2, 3.17]); return { q: T`In the titration of a weak acid with NaOH, the pH at half-equivalence is ${NUM(pk)}. What is the $pK_a$ of the acid?`, a: pk, w: [sig(pk * 2, 3), sig(14 - pk, 3), 7], s: T`At half-equivalence $[\ce{HA}] = [\ce{A-}]$, so pH $= pK_a = ${M(pk)}$.` }; },
  ],
},
{
  id: 'buffers-salts', stage: 'sh', title: 'Buffers & Salt Hydrolysis',
  blurb: 'Acidic, basic and neutral salts, hydrolysis and the pH of salt solutions, buffer solutions, how they resist pH change, the Henderson–Hasselbalch equation, and blood as a buffer.',
  lesson: () => T`
<p>Salts are not always neutral. The ion from a <b>weak</b> acid or base reacts with water (<b>hydrolysis</b>): $\ce{CH3COO- + H2O <=> CH3COOH + OH-}$ makes sodium ethanoate solution basic; $\ce{NH4+ + H2O <=> NH3 + H3O+}$ makes ammonium chloride solution acidic.</p>
${Tbl([T`Salt made from`, T`Example`, T`Solution`], [[T`strong acid + strong base`, '$\\ce{NaCl}$, $\\ce{KNO3}$', T`neutral (pH 7)`], [T`weak acid + strong base`, '$\\ce{CH3COONa}$, $\\ce{Na2CO3}$', T`basic (pH > 7)`], [T`strong acid + weak base`, '$\\ce{NH4Cl}$, $\\ce{(NH4)2SO4}$', T`acidic (pH < 7)`]])}
${Key(T`<p>For a basic salt $[\ce{OH-}] = \sqrt{\frac{K_w}{K_a} \cdot c}$; for an acidic salt $[\ce{H+}] = \sqrt{\frac{K_w}{K_b} \cdot c}$.</p>`)}
<h3>Buffers</h3>
<p>A <b>buffer</b> keeps the pH almost constant when a little acid or base is added. It contains a weak acid and its conjugate base (e.g. $\ce{CH3COOH}$ + $\ce{CH3COONa}$) or a weak base and its conjugate acid ($\ce{NH3}$ + $\ce{NH4Cl}$). Added $\ce{H+}$ is taken up by $\ce{A-}$; added $\ce{OH-}$ is neutralised by $\ce{HA}$.</p>
${Fig(planeSvg({ W: 420, H: 250, x: [0, 105], y: [0, 7.5], step: [10, 1], tickX: 20, tickY: 1, xl: T`0.1 M HCl added (mL)`, yl: 'pH', fns: [{ f: v => phMix(0.02 * 1000 / (100 + v), 1.8e-5, 10 / (100 + v), 0.1 * v / (100 + v)), from: 0, to: 100, cls: 'mf-c1', label: T`buffer`, at: 30, dx: 0, dy: -10, anchor: 'middle' }, { f: v => (v === 0 ? 7 : phMix(0, 1, 0, 0.1 * v / (100 + v))), from: 0, to: 100, n: 400, cls: 'mf-c4', label: T`pure water`, at: 30, dx: 0, dy: 18, anchor: 'middle' }], label: T`Adding hydrochloric acid to pure water makes the pH fall at once from 7 to about 2; the buffer stays near pH 4.7 until its ethanoate is used up` }), T`Adding 0.1 M HCl to 100 mL of pure water and to 100 mL of a buffer (0.1 M ethanoic acid + 0.1 M sodium ethanoate), calculated. One drop sends water from pH 7 to about 4; the buffer barely moves until almost all its ethanoate has reacted (100 mL).`)}
${Key(T`<p><b>Henderson–Hasselbalch equation:</b> $$\mathrm{pH} = pK_a + \log\frac{[\ce{A-}]}{[\ce{HA}]} \qquad [\ce{H+}] = K_a \frac{[\ce{HA}]}{[\ce{A-}]}$$ A buffer works best when $[\ce{HA}] \approx [\ce{A-}]$, i.e. at pH ≈ $pK_a$ ± 1.</p>`)}
${Tip(T`<p>Blood is buffered at pH 7.35–7.45, mainly by $\ce{H2CO3}$/$\ce{HCO3-}$; inside cells phosphate buffers ($\ce{H2PO4-}$/$\ce{HPO4^2-}$) work too. A change of just 0.2 pH units can be life-threatening.</p>`)}`,
  gens: [
    () => { const [s, t] = pick([['NaCl', 0], ['KNO3', 0], ['Na2SO4', 0], ['CH3COONa', 1], ['Na2CO3', 1], ['KF', 1], ['NH4Cl', 2], ['(NH4)2SO4', 2], ['NH4NO3', 2]]), N = [T`neutral`, T`basic`, T`acidic`]; return { q: T`Is an aqueous solution of $\ce{${s}}$ acidic, neutral or basic?`, a: N[t], w: N.filter((_, i) => i !== t), only: 'mc', s: t === 0 ? T`From a strong acid and a strong base: <b>neutral</b>.` : t === 1 ? T`The anion comes from a weak acid and hydrolyses to give $\ce{OH-}$: <b>basic</b>.` : T`$\ce{NH4+}$ comes from a weak base and hydrolyses to give $\ce{H3O+}$: <b>acidic</b>.` }; },
    () => { const r = pick([0.1, 0.5, 1, 2, 10]), pk = 4.74, p = sig(pk + lg(r), 3); return { q: T`A buffer contains ethanoic acid ($pK_a = 4.74$) and sodium ethanoate with $\frac{[\ce{A-}]}{[\ce{HA}]} = ${M(r)}$. What is its pH?`, a: p, rtol: 0.005, w: [sig(pk - lg(r), 3), pk === p ? sig(pk + 1, 3) : pk, sig(pk * r, 3)], s: T`pH $= 4.74 + \log ${M(r)} = ${M(p)}$.` }; },
    () => { const na = pick([0.1, 0.2, 0.05]), ha = pick([0.1, 0.2, 0.05].filter(x => x !== na)), Ka = 1.8e-5, h = Ka * ha / na, p = sig(-lg(h), 3); return { q: T`Find the pH of a buffer containing ${NUM(ha)} M $\ce{CH3COOH}$ and ${NUM(na)} M $\ce{CH3COONa}$ ($K_a = 1.8 \times 10^{-5}$).`, a: p, rtol: 0.005, w: [sig(-lg(Ka * na / ha), 3), sig(-lg(Math.sqrt(Ka * ha)), 3), 4.74], s: T`$[\ce{H+}] = K_a \frac{[\ce{HA}]}{[\ce{A-}]} = 1.8 \times 10^{-5} \times \frac{${M(ha)}}{${M(na)}} = ${sciT(sig(h, 3))}$ M; pH $= ${M(p)}$.` }; },
    () => { const c = pick([0.1, 0.01, 0.2]), Ka = 1.8e-5, oh = Math.sqrt(1e-14 / Ka * c), p = sig(14 + lg(oh), 3); return { q: T`Find the pH of ${NUM(c)} M sodium ethanoate ($K_a$ of ethanoic acid $= 1.8 \times 10^{-5}$).`, a: p, rtol: 0.005, w: [7, sig(-lg(oh), 3), sig(14 + lg(c), 3)], s: T`$[\ce{OH-}] = \sqrt{\frac{10^{-14}}{1.8 \times 10^{-5}} \times ${M(c)}} = ${sciT(sig(oh, 3))}$ M; pOH $= ${M(sig(-lg(oh), 3))}$; pH $= ${M(p)}$.` }; },
    () => { const [m, a] = pick([[T`CH₃COOH and CH₃COONa`, T`yes`], [T`NH₃ and NH₄Cl`, T`yes`], [T`H₂CO₃ and NaHCO₃`, T`yes`], [T`HCl and NaCl`, T`no`], [T`NaOH and NaCl`, T`no`], [T`HNO₃ and KNO₃`, T`no`]]); return { q: T`Is a mixture of ${m} a buffer?`, a, w: [a === T`yes` ? T`no` : T`yes`], only: 'mc', s: a === T`yes` ? T`A weak acid (or base) with its conjugate: <b>yes</b>.` : T`A strong acid or base has no useful conjugate partner: <b>no</b>.` }; },
  ],
},
{
  id: 'solubility-product', stage: 'sh', title: 'Solubility Product (Ksp)',
  blurb: 'Solubility equilibria of sparingly soluble salts, the solubility product Ksp, calculating solubility from Ksp and back, the common-ion effect, and predicting precipitation.',
  lesson: () => T`
<p>Even "insoluble" salts dissolve a tiny amount. In a saturated solution the undissolved solid is in dynamic equilibrium with its ions: $$\ce{AgCl(s) <=> Ag+(aq) + Cl-(aq)}$$</p>
${Fig(saturatedSvg({ label: T`A saturated silver chloride solution: solid at the bottom in equilibrium with silver and chloride ions` }), T`In a saturated solution ions leave the solid and return to it at the same rate.`)}
${Key(T`<p>The <b>solubility product</b> is the equilibrium constant (the solid is left out): $$K_{sp} = [\ce{Ag+}][\ce{Cl-}] = 1.8 \times 10^{-10}\ (25\ °\mathrm{C})$$ For a salt $\ce{M_xA_y}$ with solubility $s$ mol/L: $K_{sp} = (xs)^x(ys)^y$. So for AB, $K_{sp} = s^2$; for $\ce{AB2}$ (or $\ce{A2B}$), $K_{sp} = 4s^3$.</p>`)}
${Ex(T`<p>Solubility of $\ce{CaF2}$ ($K_{sp} = 3.9 \times 10^{-11}$): $4s^3 = 3.9 \times 10^{-11}$, $s = \sqrt[3]{9.75 \times 10^{-12}} = 2.1 \times 10^{-4}$ M.</p>`)}
${Key(T`<p><b>Will a precipitate form?</b> Compare the ion product $Q = [\ce{M+}][\ce{A-}]$ of the mixture with $K_{sp}$: if $Q > K_{sp}$ a precipitate forms; if $Q \le K_{sp}$ it does not.<br><b>Common-ion effect:</b> a salt is less soluble in a solution that already contains one of its ions (AgCl in NaCl solution), because the equilibrium shifts to the left.</p>`)}
${Tip(T`<p>Compare solubilities with $K_{sp}$ only for salts of the same formula type ($\ce{AgCl}$ with $\ce{AgBr}$). For different types, work out $s$ first.</p>`)}`,
  gens: [
    () => { const k = pick(KSP.filter(x => x[3] === 1 && x[4] === 1)), s = sig(Math.sqrt(k[5]), 2); return { q: T`$K_{sp}(\ce{${k[0]}}) = ${sciT(k[5], 2)}$. What is its molar solubility?`, a: `$${sciT(s, 2)}$ M`, w: [`$${sciT(sig(k[5] / 2, 2), 2)}$ M`, `$${sciT(sig(Math.cbrt(k[5] / 4), 2), 2)}$ M`, `$${sciT(sig(k[5], 2), 2)}$ M`], only: 'mc', s: T`$K_{sp} = s^2$, $s = \sqrt{${sciT(k[5], 2)}} = ${sciT(s, 2)}$ M.` }; },
    () => { const k = pick(KSP.filter(x => x[3] + x[4] === 3)), s = sig(Math.cbrt(k[5] / 4), 2); return { q: T`$K_{sp}(\ce{${k[0]}}) = ${sciT(k[5], 2)}$. What is its molar solubility?`, a: `$${sciT(s, 2)}$ M`, w: [`$${sciT(sig(Math.sqrt(k[5]), 2), 2)}$ M`, `$${sciT(sig(Math.cbrt(k[5]), 2), 2)}$ M`, `$${sciT(sig(Math.cbrt(k[5] / 2), 2), 2)}$ M`], only: 'mc', s: T`$K_{sp} = (${k[3]}s)^{${k[3]}}(${k[4]}s)^{${k[4]}} = 4s^3$, so $s = \sqrt[3]{\frac{${sciT(k[5], 2)}}{4}} = ${sciT(s, 2)}$ M.` }; },
    () => { const [f, x, y] = pick([['AgCl', 1, 1], ['BaSO4', 1, 1], ['CaF2', 1, 2], ['PbI2', 1, 2], ['Ag2CrO4', 2, 1], ['Mg(OH)2', 1, 2]]), s = pick([1e-4, 2e-5, 1e-3, 3e-4]), K = sig((x * s) ** x * (y * s) ** y, 2); return { q: T`The solubility of $\ce{${f}}$ is $${sciT(s, 2)}$ M. Calculate $K_{sp}$.`, a: `$${sciT(K, 2)}$`, w: [`$${sciT(sig(s * s, 2), 2)}$` === `$${sciT(K, 2)}$` ? `$${sciT(sig(4 * s ** 3, 2), 2)}$` : `$${sciT(sig(s * s, 2), 2)}$`, `$${sciT(sig(s ** 3, 2), 2)}$`, `$${sciT(sig(2 * s * s, 2), 2)}$`], only: 'mc', s: T`$K_{sp} = (${x}s)^{${x}}(${y}s)^{${y}} = ${sciT(K, 2)}$.` }; },
    () => { const c1 = pick([1e-3, 1e-4, 1e-5, 2e-5, 5e-6]), c2 = pick([1e-3, 1e-4, 1e-5, 1e-6]), Qp = c1 * c2, K = 1.8e-10, yes = Qp > K; return { q: T`Equal volumes are mixed so that $[\ce{Ag+}] = ${sciT(c1, 1)}$ M and $[\ce{Cl-}] = ${sciT(c2, 1)}$ M. Does AgCl precipitate? ($K_{sp} = 1.8 \times 10^{-10}$)`, a: yes ? T`yes` : T`no`, w: [yes ? T`no` : T`yes`], only: 'mc', s: T`$Q = ${sciT(c1, 1)} \times ${sciT(c2, 1)} = ${sciT(sig(Qp, 2), 2)}$ ${yes ? '>' : '≤'} $K_{sp}$: ${yes ? T`a precipitate forms` : T`no precipitate`}.` }; },
    () => { const c = pick([0.1, 0.01, 0.001]), K = 1.8e-10, s = sig(K / c, 2); return { q: T`What is the solubility of AgCl in ${NUM(c)} M NaCl? ($K_{sp} = 1.8 \times 10^{-10}$)`, a: `$${sciT(s, 2)}$ M`, w: [`$${sciT(1.3e-5, 2)}$ M`, `$${sciT(sig(K * c, 2), 2)}$ M`, `$${sciT(sig(Math.sqrt(K / c), 2), 2)}$ M`], only: 'mc', s: T`$[\ce{Cl-}] \approx ${M(c)}$ M, so $s = [\ce{Ag+}] = \frac{1.8 \times 10^{-10}}{${M(c)}} = ${sciT(s, 2)}$ M: far less than in pure water ($1.3 \times 10^{-5}$ M).` }; },
  ],
},
  ],
});
})();
