/* ==========================================================================
   TRACK H — Redox & Electrochemistry
   ========================================================================== */
(() => {
const ON = [['H2SO4', 'S', 6], ['SO2', 'S', 4], ['H2S', 'S', -2], ['Na2S2O3', 'S', 2], ['SO3', 'S', 6], ['KMnO4', 'Mn', 7], ['MnO2', 'Mn', 4], ['MnSO4', 'Mn', 2], ['K2Cr2O7', 'Cr', 6], ['Cr2O3', 'Cr', 3], ['NH3', 'N', -3], ['HNO3', 'N', 5], ['NO2', 'N', 4], ['NO', 'N', 2], ['N2O', 'N', 1], ['HClO', 'Cl', 1], ['KClO3', 'Cl', 5], ['HClO4', 'Cl', 7], ['CO2', 'C', 4], ['CH4', 'C', -4], ['CO', 'C', 2], ['Fe2O3', 'Fe', 3], ['FeO', 'Fe', 2], ['H3PO4', 'P', 5], ['H2O2', 'O', -1], ['NaH', 'H', -1], ['Cu2O', 'Cu', 1], ['CuO', 'Cu', 2]];
const sgn = n => (n > 0 ? '+' + n : n < 0 ? '−' + -n : '0');
const F = 96485;
const MET = [['Zn', -0.76], ['Fe', -0.44], ['Ni', -0.25], ['Pb', -0.13], ['Cu', 0.34], ['Ag', 0.80], ['Mg', -2.37], ['Al', -1.66]];
level({
  id: 'redox', mark: 'H', name: 'Redox & Electrochemistry', short: 'Redox', band: 'Oxidation numbers · cells · electrolysis', color: 'lv8',
  blurb: 'Oxidation and reduction as electron transfer, oxidation numbers, balancing redox equations, galvanic cells and standard electrode potentials, batteries, electrolysis and Faraday’s laws, and corrosion.',
  topics: [
{
  id: 'redox-basics', stage: 'sh', title: 'Oxidation, Reduction & Oxidation Numbers',
  blurb: 'Oxidation and reduction in terms of oxygen, hydrogen and electrons, oxidation number rules, oxidising and reducing agents, and disproportionation.',
  lesson: () => T`
<p>The word <b>oxidation</b> first meant gaining oxygen (iron rusting, fuels burning) and <b>reduction</b> meant losing it (extracting a metal from its ore). The modern definition is about electrons:</p>
${Key(T`<p><b>OIL RIG:</b> <b>O</b>xidation <b>I</b>s <b>L</b>oss of electrons, <b>R</b>eduction <b>I</b>s <b>G</b>ain. They always happen together: a <b>redox</b> reaction.</p><p>$\ce{Zn + Cu^2+ -> Zn^2+ + Cu}$: zinc loses 2 electrons (oxidised) and $\ce{Cu^2+}$ gains them (reduced).</p>`)}
${FigRow([[beakerSvg({ n: 0, level: 0.75, cls: 'ch-p2', W: 150, H: 160, label: T`A zinc strip in blue copper sulfate solution at the start` }).replace('</svg>', sR(66, 8, 16, 120, 'mf-s3l', 2, ' stroke="var(--ink-2)"') + '</svg>').replace(/class="ch-liq"/, 'class="ch-liq" style="fill:color-mix(in srgb, #2f7fd8 45%, var(--paper))"'), T`start: zinc in blue $\ce{CuSO4}$`], [beakerSvg({ n: 0, level: 0.75, cls: 'ch-p2', W: 150, H: 160, label: T`Later: copper coats the zinc and the solution becomes paler` }).replace('</svg>', sR(66, 8, 16, 120, 'mf-s3l', 2, ' stroke="var(--ink-2)"') + sR(64, 58, 20, 70, '', 3, ' style="fill:#b8653a;opacity:.85"') + '</svg>').replace(/class="ch-liq"/, 'class="ch-liq" style="fill:color-mix(in srgb, #2f7fd8 12%, var(--paper))"'), T`later: copper on the zinc, colour fades`]], T`Zinc displaces copper: brown copper forms on the zinc and the blue colour of $\ce{Cu^2+}$ fades as it is reduced.`)}
<h3>Oxidation numbers</h3>
<p>An <b>oxidation number</b> (oxidation state) is the charge an atom would have if all its bonds were ionic. An increase in oxidation number is oxidation, a decrease is reduction.</p>
${Tbl([T`Rule`, T`Example`], [[T`an uncombined element is 0`, '$\\ce{Na}$, $\\ce{O2}$, $\\ce{Cl2}$: 0'], [T`a simple ion: its charge`, '$\\ce{Fe^3+}$: +3, $\\ce{Cl-}$: −1'], [T`group 1 metals +1, group 2 metals +2, fluorine −1`, '$\\ce{NaCl}$, $\\ce{MgO}$'], [T`hydrogen +1 (−1 in metal hydrides)`, '$\\ce{H2O}$; $\\ce{NaH}$'], [T`oxygen −2 (−1 in peroxides, +2 in $\\ce{OF2}$)`, '$\\ce{H2O}$; $\\ce{H2O2}$'], [T`the sum is 0 in a compound, the charge in an ion`, '$\\ce{SO4^2-}$: $x + 4(-2) = -2$, $x = +6$']])}
${Ex(T`<p>Mn in $\ce{KMnO4}$: $+1 + x + 4(-2) = 0$, so $x = +7$. Transition metals in names: iron(III) oxide means Fe is +3.</p>`)}
${Key(T`<p>The <b>oxidising agent</b> is the species that is reduced (it takes electrons from something else); the <b>reducing agent</b> is the species that is oxidised. In $\ce{Zn + Cu^2+ -> Zn^2+ + Cu}$, $\ce{Cu^2+}$ is the oxidising agent and Zn the reducing agent. In <b>disproportionation</b> the same element is both oxidised and reduced: $\ce{Cl2 + 2NaOH -> NaCl + NaClO + H2O}$ (0 → −1 and +1).</p>`)}
${Tip(T`<p>Common oxidising agents: $\ce{O2}$, $\ce{Cl2}$, $\ce{KMnO4}$ (purple → colourless), $\ce{K2Cr2O7}$ (orange → green), $\ce{H2O2}$. Common reducing agents: metals, $\ce{H2}$, $\ce{C}$, $\ce{CO}$, $\ce{SO2}$.</p>`)}`,
  gens: [
    () => { const [f, el, n] = pick(ON); return { q: T`What is the oxidation number of ${el} in $\ce{${f}}$?`, a: sgn(n), w: [sgn(n + 2), sgn(-n || 2), sgn(n - 1)].filter((x, i, arr) => x !== sgn(n) && arr.indexOf(x) === i), only: 'mc', s: T`Use O = −2, H = +1, group 1 = +1 and a total of 0: ${el} is <b>${sgn(n)}</b>.` }; },
    () => { const [ion, el, n] = pick([['SO4^2-', 'S', 6], ['NO3-', 'N', 5], ['MnO4-', 'Mn', 7], ['Cr2O7^2-', 'Cr', 6], ['CO3^2-', 'C', 4], ['NH4+', 'N', -3], ['PO4^3-', 'P', 5], ['ClO3-', 'Cl', 5], ['SO3^2-', 'S', 4], ['NO2-', 'N', 3]]); return { q: T`What is the oxidation number of ${el} in $\ce{${ion}}$?`, a: sgn(n), w: [sgn(n + 1), sgn(n - 2), sgn(n + 2)], only: 'mc', s: T`The oxidation numbers add up to the charge of the ion: ${el} is <b>${sgn(n)}</b>.` }; },
    () => { const [e, ox, red] = pick([['\\ce{Zn + Cu^2+ -> Zn^2+ + Cu}', 'Zn', 'Cu^2+'], ['\\ce{Mg + 2H+ -> Mg^2+ + H2}', 'Mg', 'H+'], ['\\ce{Cl2 + 2Br- -> 2Cl- + Br2}', 'Br-', 'Cl2'], ['\\ce{Fe2O3 + 3CO -> 2Fe + 3CO2}', 'CO', 'Fe2O3'], ['\\ce{2Fe^2+ + Cl2 -> 2Fe^3+ + 2Cl-}', 'Fe^2+', 'Cl2'], ['\\ce{CuO + H2 -> Cu + H2O}', 'H2', 'CuO']]), ask = chance(); return ask ? { q: T`In $${e}$, which species is the reducing agent?`, a: `$\\ce{${ox}}$`, w: [`$\\ce{${red}}$`, T`neither`], only: 'mc', s: T`$\ce{${ox}}$ is oxidised (loses electrons), so it is the reducing agent.` } : { q: T`In $${e}$, which species is the oxidising agent?`, a: `$\\ce{${red}}$`, w: [`$\\ce{${ox}}$`, T`neither`], only: 'mc', s: T`$\ce{${red}}$ is reduced (gains electrons), so it is the oxidising agent.` }; },
    () => { const [h, t] = pick([['\\ce{Fe^2+ -> Fe^3+ + e-}', 0], ['\\ce{Cu^2+ + 2e- -> Cu}', 1], ['\\ce{2Cl- -> Cl2 + 2e-}', 0], ['\\ce{O2 + 4e- -> 2O^2-}', 1], ['\\ce{Na -> Na+ + e-}', 0], ['\\ce{2H+ + 2e- -> H2}', 1]]), N = [T`oxidation`, T`reduction`]; return { q: T`Is $${h}$ an oxidation or a reduction?`, a: N[t], w: [N[1 - t]], only: 'mc', s: t ? T`Electrons are gained: <b>reduction</b>.` : T`Electrons are lost: <b>oxidation</b>.` }; },
    () => { const [e, t] = pick([['\\ce{Zn + 2HCl -> ZnCl2 + H2}', 1], ['\\ce{NaOH + HCl -> NaCl + H2O}', 0], ['\\ce{2Mg + O2 -> 2MgO}', 1], ['\\ce{AgNO3 + NaCl -> AgCl + NaNO3}', 0], ['\\ce{CaCO3 -> CaO + CO2}', 0], ['\\ce{Cl2 + 2KI -> 2KCl + I2}', 1], ['\\ce{CH4 + 2O2 -> CO2 + 2H2O}', 1]]); return { q: T`Is $${e}$ a redox reaction?`, a: t ? T`yes` : T`no`, w: [t ? T`no` : T`yes`], only: 'mc', s: t ? T`Oxidation numbers change: <b>yes</b>.` : T`No oxidation number changes: <b>no</b>.` }; },
  ],
},
{
  id: 'balancing-redox', stage: 'sh', title: 'Half-Equations & Balancing Redox Equations',
  blurb: 'Writing half-equations, the ion–electron method in acidic and basic solution, and the oxidation-number method for balancing redox equations.',
  lesson: () => T`
<p>A redox equation can be split into two <b>half-equations</b>, one for oxidation and one for reduction. The electrons lost must equal the electrons gained.</p>
${Fig(flowSvg([T`1. write the two half-equations`, T`2. balance atoms other than O and H`, T`3. balance O with H₂O`, T`4. balance H with H⁺`, T`5. balance charge with e⁻`, T`6. multiply so the electrons cancel, then add`], { W: 440, label: T`Six steps of the ion–electron method for balancing a redox equation in acidic solution` }), T`The ion–electron (half-reaction) method in acidic solution. In basic solution, finish in acid and then add $\ce{OH-}$ to both sides to turn every $\ce{H+}$ into $\ce{H2O}$.`)}
${Ex(T`<p>Balance $\ce{MnO4- + Fe^2+ -> Mn^2+ + Fe^3+}$ in acid.</p><p>Reduction: $\ce{MnO4- + 8H+ + 5e- -> Mn^2+ + 4H2O}$<br>Oxidation: $\ce{Fe^2+ -> Fe^3+ + e-}$ (× 5)<br>Sum: $$\ce{MnO4- + 8H+ + 5Fe^2+ -> Mn^2+ + 5Fe^3+ + 4H2O}$$ Check: charge $-1 + 8 + 10 = +17$ on the left, $+2 + 15 = +17$ on the right ✓.</p>`)}
${Key(T`<p><b>Oxidation-number method:</b> find the change in oxidation number of the atoms oxidised and reduced, and choose coefficients so the total increase equals the total decrease; then balance the other atoms. In $\ce{Cu + HNO3 -> Cu(NO3)2 + NO + H2O}$: Cu 0 → +2 (up 2), N +5 → +2 (down 3), so 3 Cu for every 2 NO: $$\ce{3Cu + 8HNO3 -> 3Cu(NO3)2 + 2NO + 4H2O}$$</p>`)}
${Tip(T`<p>This reaction is the basis of redox titrations: purple $\ce{MnO4-}$ turns colourless as long as $\ce{Fe^2+}$ remains, so the first permanent pink colour marks the end point with no extra indicator needed.</p>`)}`,
  gens: [
    () => { const [h, n] = pick([['\\ce{MnO4- + 8H+ + ?e- -> Mn^2+ + 4H2O}', 5], ['\\ce{Cr2O7^2- + 14H+ + ?e- -> 2Cr^3+ + 7H2O}', 6], ['\\ce{Cl2 + ?e- -> 2Cl-}', 2], ['\\ce{Fe^3+ + ?e- -> Fe^2+}', 1], ['\\ce{NO3- + 4H+ + ?e- -> NO + 2H2O}', 3], ['\\ce{O2 + 4H+ + ?e- -> 2H2O}', 4], ['\\ce{H2O2 + 2H+ + ?e- -> 2H2O}', 2]]); return { q: T`How many electrons (?) balance the half-equation $${h}$?`, a: n, w: [n + 1, n + 2, Math.max(1, n - 1) === n ? n + 3 : Math.max(1, n - 1)], s: T`Make the charges equal on both sides: <b>${n}</b> electrons.` }; },
    () => { const [a, b, ea, eb] = pick([['\\ce{MnO4-}', '\\ce{Fe^2+}', 5, 1], ['\\ce{Cr2O7^2-}', '\\ce{Fe^2+}', 6, 1], ['\\ce{MnO4-}', '\\ce{C2O4^2-}', 5, 2], ['\\ce{Cr2O7^2-}', '\\ce{I-}', 6, 1], ['\\ce{MnO4-}', '\\ce{H2O2}', 5, 2]]), g = (x, y) => (y ? g(y, x % y) : x), l = ea * eb / g(ea, eb), r = (l / eb) / (l / ea); return { q: T`$${a}$ gains ${ea} electrons per ion or molecule and $${b}$ loses ${eb}. What is the mole ratio ${b.replace(/\\ce\{|\}/g, '')} : ${a.replace(/\\ce\{|\}/g, '')} in the balanced equation?`, a: `${l / eb} : ${l / ea}`, w: [`${l / ea} : ${l / eb}`, `1 : 1`, `${ea} : ${eb * 2}`].filter(x => x !== `${l / eb} : ${l / ea}`), only: 'mc', s: T`Electrons must cancel: ${l / eb} × ${eb} = ${l / ea} × ${ea} = ${l} electrons, so ${l / eb} : ${l / ea}.` }; },
    () => { const [e, co] = pick([['\\ce{Cu + HNO3 -> Cu(NO3)2 + NO + H2O}', [3, 8, 3, 2, 4]], ['\\ce{MnO2 + HCl -> MnCl2 + Cl2 + H2O}', [1, 4, 1, 1, 2]], ['\\ce{Fe2O3 + CO -> Fe + CO2}', [1, 3, 2, 3]], ['\\ce{H2S + SO2 -> S + H2O}', [2, 1, 3, 2]], ['\\ce{Al + O2 -> Al2O3}', [4, 3, 2]]]), k = randInt(0, co.length - 1), parts = e.replace(/\\ce\{|\}$/g, '').split(/ \+ | -> /); return { q: T`Balance $${e}$. What is the coefficient of $\ce{${parts[k]}}$?`, a: co[k], w: [co[k] + 1, co[k] * 2, Math.max(1, co[k] - 1) === co[k] ? co[k] + 2 : Math.max(1, co[k] - 1)], s: T`Coefficients: ${co.join(', ')}.` }; },
    () => { const c = pick([0.02, 0.01, 0.05]), V = pick([20, 15, 25, 12.5]), Vf = 25, n = c * V / 1000 * 5, cf = sig(n / (Vf / 1000), 3); return { q: T`${Q(V, 'mL')} of ${M(c)} M $\ce{KMnO4}$ reacts with ${Q(Vf, 'mL')} of $\ce{Fe^2+}$ solution ($\ce{MnO4- + 5Fe^2+ + 8H+ -> Mn^2+ + 5Fe^3+ + 4H2O}$). What is $[\ce{Fe^2+}]$ (in M)?`, a: cf, u: 'M', rtol: 0.01, w: [sig(cf / 5, 3), sig(cf / 25, 3), sig(c * V / Vf, 3) === cf ? sig(cf * 2, 3) : sig(c * V / Vf, 3)], s: T`$n(\ce{MnO4-}) = ${M(c)} \times ${M(V / 1000)} = ${sciT(sig(c * V / 1000, 3))}$ mol; × 5 $= ${sciT(sig(n, 3))}$ mol $\ce{Fe^2+}$; $c = \frac{${sciT(sig(n, 3))}}{0.025} = ${M(cf)}$ M.` }; },
  ],
},
{
  id: 'galvanic-cells', stage: 'sh', title: 'Galvanic Cells & Electrode Potentials',
  blurb: 'Galvanic (voltaic) cells, the salt bridge, anode and cathode, cell notation, standard electrode potentials, calculating E°cell, predicting spontaneous reactions, the reactivity series and practical batteries.',
  lesson: () => T`
<p>If the two halves of a redox reaction are separated, the electrons must travel through a wire: the reaction produces an electric current. This is a <b>galvanic</b> (voltaic) <b>cell</b>.</p>
${Fig(galvanicCellSvg({ names: [T`anode`, T`cathode`, T`salt bridge (KNO₃)`, T`ZnSO₄(aq)`, T`CuSO₄(aq)`], label: T`Daniell cell: a zinc electrode in zinc sulfate and a copper electrode in copper sulfate, joined by a wire through a voltmeter and by a salt bridge` }), T`The Daniell cell. Zinc is oxidised at the <b>anode</b> ($\ce{Zn -> Zn^2+ + 2e-}$); electrons flow through the wire to the copper <b>cathode</b>, where $\ce{Cu^2+ + 2e- -> Cu}$. The salt bridge lets ions move to keep both solutions neutral. Standard voltage 1.10 V.`)}
${Key(T`<p><b>Cell notation:</b> anode on the left, cathode on the right, | for a phase boundary, ‖ for the salt bridge: $$\ce{Zn(s) | Zn^2+(aq) || Cu^2+(aq) | Cu(s)}$$ <b>Standard electrode potentials</b> $E^\circ$ are measured against the standard hydrogen electrode (0.00 V) at 25 °C, 1 M, 1 bar. $$E^\circ_{\text{cell}} = E^\circ_{\text{cathode}} - E^\circ_{\text{anode}}$$ The reaction is spontaneous if $E^\circ_{\text{cell}} > 0$.</p>`)}
${FigW(eLadderSvg({ names: [T`stronger oxidising agents`, T`stronger reducing agents`], label: T`Standard reduction potentials from lithium at minus 3.04 volts to fluorine at plus 2.87 volts` }), T`Standard reduction potentials (CRC Handbook). Species at the top left are the strongest oxidising agents ($\ce{F2}$); those at the bottom right are the strongest reducing agents (Li). A metal lower down displaces the ions of a metal higher up: zinc displaces copper, but copper does not displace zinc.`)}
${Ex(T`<p>Ag/Cu cell: cathode Ag ($+0.80$ V), anode Cu ($+0.34$ V): $E^\circ_{\text{cell}} = 0.80 - 0.34 = 0.46$ V, reaction $\ce{Cu + 2Ag+ -> Cu^2+ + 2Ag}$.</p>`)}
${Tip(T`<p>Practical cells: the zinc–carbon and alkaline dry cells (1.5 V, not rechargeable), the lead–acid car battery (2 V per cell, rechargeable), lithium-ion batteries in phones and electric cars (about 3.7 V), and hydrogen fuel cells ($\ce{2H2 + O2 -> 2H2O}$, 1.23 V).</p>`)}`,
  gens: [
    () => { const [[a, ea], [b, eb]] = [...MET].sort(() => rng() - 0.5).slice(0, 2).sort((p, q) => p[1] - q[1]), E = sig(eb - ea, 3); return { q: T`A cell is made from ${a}/${a}ⁿ⁺ ($E^\circ = ${M(ea)}$ V) and ${b}/${b}ⁿ⁺ ($E^\circ = ${M(eb)}$ V). What is $E^\circ_{\text{cell}}$ (in V)?`, a: E, u: 'V', rtol: 0.005, w: [sig(ea + eb, 3), sig(ea - eb, 3), sig(Math.abs(ea) + Math.abs(eb), 3) === E ? sig(E * 2, 3) : sig(Math.abs(ea) + Math.abs(eb), 3)], s: T`The higher $E^\circ$ (${b}) is the cathode: $E^\circ_{\text{cell}} = ${M(eb)} - (${M(ea)}) = ${M(E)}$ V.` }; },
    () => { const [[a, ea], [b, eb]] = [...MET].sort(() => rng() - 0.5).slice(0, 2).sort((p, q) => p[1] - q[1]), ask = chance(); return { q: ask ? T`In a cell made of ${a} and ${b} electrodes, which metal is the anode?` : T`In a cell made of ${a} and ${b} electrodes, which metal is the positive electrode (cathode)?`, a: ask ? a : b, w: [ask ? b : a, T`both`], only: 'mc', s: T`${a} has the lower $E^\circ$ (${M(ea)} V), so it is oxidised: ${a} is the anode (−) and ${b} the cathode (+).` }; },
    () => { const [[m, em], [ion, ei]] = [...MET].sort(() => rng() - 0.5).slice(0, 2), yes = em < ei; return { q: T`Will ${m} metal react with a solution of ${ion} ions? ($E^\circ$: ${m} ${M(em)} V, ${ion} ${M(ei)} V)`, a: yes ? T`yes` : T`no`, w: [yes ? T`no` : T`yes`], only: 'mc', s: yes ? T`${m} has the lower $E^\circ$, so it can reduce ${ion} ions: $E^\circ_{\text{cell}} = ${M(sig(ei - em, 3))}$ V > 0.` : T`$E^\circ_{\text{cell}} = ${M(sig(ei - em, 3))}$ V < 0: no reaction.` }; },
    () => { const [n, a, b] = pick([[T`zinc–copper`, '\\ce{Zn(s) | Zn^2+(aq) || Cu^2+(aq) | Cu(s)}', '\\ce{Cu(s) | Cu^2+(aq) || Zn^2+(aq) | Zn(s)}'], [T`magnesium–silver`, '\\ce{Mg(s) | Mg^2+(aq) || Ag+(aq) | Ag(s)}', '\\ce{Ag(s) | Ag+(aq) || Mg^2+(aq) | Mg(s)}'], [T`iron–copper`, '\\ce{Fe(s) | Fe^2+(aq) || Cu^2+(aq) | Cu(s)}', '\\ce{Cu(s) | Cu^2+(aq) || Fe^2+(aq) | Fe(s)}']]); return { q: T`Which is the correct cell notation for the ${n} cell?`, a: `$${a}$`, w: [`$${b}$`, `$${a.replace('||', '|')}$`], only: 'mc', s: T`Anode (lower $E^\circ$) on the left: $${a}$.` }; },
    () => pick([
      { q: T`What is the purpose of the salt bridge?`, a: T`To let ions flow so both solutions stay electrically neutral`, w: [T`To carry electrons between the beakers`, T`To increase the voltage`, T`To stop the reaction`], only: 'mc', s: T`Electrons go through the wire; ions move through the salt bridge.` },
      { q: T`In a galvanic cell, where does oxidation occur?`, a: T`at the anode`, w: [T`at the cathode`, T`in the salt bridge`, T`in the voltmeter`], only: 'mc', s: T`An Ox, Red Cat: oxidation at the anode, reduction at the cathode.` },
    ]),
  ],
},
{
  id: 'electrolysis', stage: 'sh', title: 'Electrolysis & Faraday’s Laws',
  blurb: 'Electrolysis of molten and aqueous compounds, predicting the products at each electrode, electroplating and refining, industrial electrolysis, and Faraday’s laws.',
  lesson: () => T`
<p>In <b>electrolysis</b> an electric current forces a non-spontaneous redox reaction to happen. The liquid that conducts (a molten ionic compound or a solution of ions) is the <b>electrolyte</b>. Positive ions (cations) move to the negative electrode, the <b>cathode</b>, and are reduced; negative ions (anions) move to the positive <b>anode</b> and are oxidised.</p>
${Fig(electrolysisSvg({ names: [T`cathode (−)`, T`anode (+)`], label: T`Electrolysis of copper chloride solution: copper forms at the cathode, chlorine gas bubbles at the anode` }), T`Electrolysis of $\ce{CuCl2(aq)}$ with inert graphite electrodes: $\ce{Cu^2+ + 2e- -> Cu}$ at the cathode, $\ce{2Cl- -> Cl2 + 2e-}$ at the anode.`)}
${Key(T`<p><b>Molten</b> compound: the metal forms at the cathode and the non-metal at the anode ($\ce{NaCl(l)}$ gives Na and $\ce{Cl2}$).<br><b>Aqueous</b> solution: water can react too.<br>Cathode: a metal below hydrogen in reactivity (Cu, Ag) is deposited; otherwise (Na, K, Mg, Al) hydrogen is produced.<br>Anode (inert electrodes): chlorine, bromine or iodine from concentrated halides; otherwise ($\ce{SO4^2-}$, $\ce{NO3-}$) oxygen is produced from water.</p>`)}
${Tbl([T`Electrolyte (inert electrodes)`, T`At the cathode`, T`At the anode`], [['$\\ce{NaCl(l)}$', 'Na', '$\\ce{Cl2}$'], [T`$\\ce{NaCl(aq)}$, concentrated`, '$\\ce{H2}$', '$\\ce{Cl2}$'], ['$\\ce{CuSO4(aq)}$', 'Cu', '$\\ce{O2}$'], [T`$\\ce{H2SO4(aq)}$, dilute`, '$\\ce{H2}$', '$\\ce{O2}$'], ['$\\ce{KI(aq)}$', '$\\ce{H2}$', '$\\ce{I2}$']])}
<h3>Faraday's laws</h3>
${Fm(T`Q = I\,t \qquad n(e^-) = \frac{Q}{F} \qquad m = \frac{I\,t\,M}{z\,F}`)}
<p>where $F = 96\,485$ C/mol is the Faraday constant (the charge of one mole of electrons) and $z$ the number of electrons per ion. The mass deposited is proportional to the charge passed.</p>
${Ex(T`<p>A current of 2.00 A for 30.0 min through $\ce{CuSO4}$: $Q = 2.00 \times 1800 = 3600$ C; $n(e^-) = \frac{3600}{96\,485} = 0.0373$ mol; $n(\ce{Cu}) = 0.0187$ mol; $m = 0.0187 \times 63.5 = 1.18$ g.</p>`)}
${Tip(T`<p>Uses: aluminium extraction from molten alumina in cryolite (Hall–Héroult), the chlor-alkali industry ($\ce{Cl2}$, $\ce{H2}$ and NaOH from brine), purifying copper (impure anode, pure cathode), and electroplating (the object to be plated is the cathode).</p>`)}`,
  gens: [
    () => { const [el, c, a] = pick([[T`molten sodium chloride`, 'Na', 'Cl₂'], [T`molten lead(II) bromide`, 'Pb', 'Br₂'], [T`concentrated aqueous sodium chloride`, 'H₂', 'Cl₂'], [T`aqueous copper(II) sulfate`, 'Cu', 'O₂'], [T`dilute sulfuric acid`, 'H₂', 'O₂'], [T`aqueous potassium iodide`, 'H₂', 'I₂'], [T`aqueous silver nitrate`, 'Ag', 'O₂'], [T`molten aluminium oxide`, 'Al', 'O₂']]), ask = chance(); return { q: ask ? T`What forms at the cathode in the electrolysis of ${el} (inert electrodes)?` : T`What forms at the anode in the electrolysis of ${el} (inert electrodes)?`, a: ask ? c : a, w: ['Na', 'H₂', 'Cu', 'Cl₂', 'O₂', 'Ag', 'Pb', 'Br₂', 'I₂', 'Al'].filter(x => x !== (ask ? c : a)).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`Cathode: <b>${c}</b>; anode: <b>${a}</b>.` }; },
    () => { const I = pick([1, 2, 2.5, 5, 0.5]), t = pick([10, 20, 30, 60]), [m0, M0, z] = pick([['Cu', 63.5, 2], ['Ag', 108, 1], ['Zn', 65.4, 2], ['Ni', 58.7, 2], ['Al', 27, 3]]), m = sig(I * t * 60 * M0 / (z * F), 3); return { q: T`A current of ${Q(I, 'A')} flows for ${t} min, depositing ${m0} (${z === 1 ? m0 + '⁺' : m0 + (z === 2 ? '²⁺' : '³⁺')}, $M = ${M0}$ g/mol). What mass is deposited (in g)? ($F = 96\,485$ C/mol)`, a: m, u: 'g', rtol: 0.01, w: [sig(m * z, 3), sig(I * t * M0 / (z * F), 3), sig(m / z, 3)].filter(x => x !== m), s: T`$Q = ${M(I)} \times ${t * 60} = ${M(I * t * 60)}$ C; $m = \frac{Q M}{zF} = \frac{${M(I * t * 60)} \times ${M0}}{${z} \times 96\,485} = ${M(m)}$ g.` }; },
    () => { const I = pick([2, 3, 4, 5]), h = pick([1, 2, 0.5]), Q0 = I * h * 3600, n = sig(Q0 / F, 3); return { q: T`How many moles of electrons pass when ${Q(I, 'A')} flows for ${M(h)} h? ($F = 96\,485$ C/mol)`, a: n, u: 'mol', rtol: 0.01, w: [sig(I * h / F, 3), sig(Q0 / F / 2, 3), sig(I * h * 60 / F, 3)], s: T`$Q = ${M(I)} \times ${M(h * 3600)} = ${M(Q0)}$ C; $n = \frac{${M(Q0)}}{96\,485} = ${M(n)}$ mol.` }; },
    () => pick([
      { q: T`In electroplating a spoon with silver, the spoon is…`, a: T`the cathode`, w: [T`the anode`, T`the electrolyte`, T`the salt bridge`], only: 'mc', s: T`$\ce{Ag+}$ ions are reduced on the spoon, so it must be the cathode.` },
      { q: T`Why must an ionic compound be molten or dissolved to be electrolysed?`, a: T`So its ions can move to the electrodes`, w: [T`So it contains electrons`, T`So it becomes covalent`, T`So it can burn`], only: 'mc', s: T`In the solid the ions are fixed in the lattice.` },
      { q: T`Why is aluminium extracted by electrolysis and not by heating with carbon?`, a: T`Aluminium is more reactive than carbon`, w: [T`Aluminium ore contains no oxygen`, T`Carbon is too expensive`, T`Electrolysis is faster`], only: 'mc', s: T`Carbon cannot reduce aluminium oxide.` },
    ]),
  ],
},
{
  id: 'corrosion', stage: 'jh', title: 'Corrosion & Its Prevention',
  blurb: 'Rusting of iron as an electrochemical process, the conditions for rusting, and ways to prevent it: barriers, galvanising, sacrificial protection and alloys.',
  lesson: () => T`
<p><b>Corrosion</b> is the slow destruction of a metal by reaction with its environment. The corrosion of iron is called <b>rusting</b>; rust is hydrated iron(III) oxide, $\ce{Fe2O3.xH2O}$. Unlike the thin oxide layer on aluminium, rust is flaky and falls off, so fresh iron keeps being exposed.</p>
${Fig(rustTubesSvg({ names: [T`air + water: rusts`, T`boiled water + oil: no rust`, T`dry air (drying agent): no rust`], label: T`Three test tubes with iron nails: in air and water the nail rusts; in boiled water under oil and in dry air it does not` }), T`The classic experiment: iron rusts only when <b>both oxygen and water</b> are present. Boiling removes dissolved air and the oil layer keeps it out; calcium chloride keeps the air dry. Salt water speeds rusting up.`)}
${Key(T`<p>Rusting is electrochemical. Part of the iron surface acts as an anode: $\ce{Fe -> Fe^2+ + 2e-}$. The electrons flow through the metal to where oxygen is reduced: $\ce{O2 + 2H2O + 4e- -> 4OH-}$. $\ce{Fe^2+}$ and $\ce{OH-}$ form $\ce{Fe(OH)2}$, which is oxidised further to rust.</p>`)}
${Tbl([T`Method`, T`How it works`, T`Examples`], [[T`barrier: paint, oil, grease, plastic`, T`keeps out air and water`, T`cars, bicycle chains, fences`], [T`galvanising (zinc coating)`, T`barrier, and zinc corrodes first even if scratched`, T`buckets, roofs, lamp posts`], [T`sacrificial protection`, T`a more reactive metal (Zn, Mg) is joined to the iron and is oxidised instead`, T`ships’ hulls, underground pipes`], [T`tin plating`, T`barrier only; if scratched the iron rusts faster`, T`food cans`], [T`alloying`, T`stainless steel contains chromium and nickel, which form a protective oxide layer`, T`cutlery, sinks`], [T`cathodic protection`, T`a power supply makes the iron the cathode`, T`pipelines, bridges`]])}
${Tip(T`<p>Corrosion costs about 3–4% of the world's GDP every year (NACE International, 2016). Aluminium, zinc and chromium look reactive on paper but resist corrosion because a thin, tight oxide layer protects them.</p>`)}`,
  gens: [
    () => { const [c, a] = pick([[T`an iron nail in boiled water covered with oil`, T`no`], [T`an iron nail in dry air with calcium chloride`, T`no`], [T`an iron nail in tap water open to the air`, T`yes`], [T`an iron nail in salt water`, T`yes, faster`], [T`an iron nail wrapped in zinc in salt water`, T`no`], [T`an iron nail wrapped in copper in salt water`, T`yes, faster`]]); return { q: T`Does ${c} rust?`, a, w: [T`no`, T`yes`, T`yes, faster`].filter(x => x !== a), only: 'mc', s: a === T`no` ? T`Rusting needs both water and oxygen, or zinc protects the iron: <b>no</b>.` : T`Water and oxygen are present${a === T`yes, faster` ? T`; salt or a less reactive metal speeds it up` : ''}: <b>${a}</b>.` }; },
    () => { const [m, a] = pick([[T`magnesium`, T`yes`], [T`zinc`, T`yes`], [T`copper`, T`no`], [T`tin`, T`no`], [T`aluminium`, T`yes`], [T`silver`, T`no`]]); return { q: T`Could ${m} be used as a sacrificial metal to protect iron?`, a, w: [a === T`yes` ? T`no` : T`yes`], only: 'mc', s: a === T`yes` ? T`It is more reactive than iron, so it is oxidised first: <b>yes</b>.` : T`It is less reactive than iron, so the iron would corrode instead: <b>no</b>.` }; },
    () => pick([
      { q: T`What two substances are needed for iron to rust?`, a: T`oxygen and water`, w: [T`oxygen and carbon dioxide`, T`water and salt`, T`nitrogen and water`], only: 'mc', s: T`Both oxygen and water.` },
      { q: T`Why does galvanised iron not rust even when scratched?`, a: T`Zinc is more reactive and corrodes instead of the iron`, w: [T`Zinc is a better barrier than paint`, T`Zinc reacts with rust`, T`Scratches fill with zinc oxide paint`], only: 'mc', s: T`Sacrificial protection by the zinc.` },
      { q: T`What is rust?`, a: T`hydrated iron(III) oxide`, w: [T`iron(II) chloride`, T`iron carbonate`, T`pure iron oxide Fe₃O₄`], only: 'mc', s: T`$\ce{Fe2O3.xH2O}$.` },
      { q: T`Why does aluminium not corrode like iron?`, a: T`A thin, tight oxide layer protects it`, w: [T`It is unreactive`, T`It does not contain electrons`, T`It is always painted`], only: 'mc', s: T`$\ce{Al2O3}$ sticks to the surface and seals it.` },
    ]),
  ],
},
  ],
});
})();
