/* ==========================================================================
   TRACK I — Organic Chemistry
   ========================================================================== */
(() => {
const STEM = ['meth', 'eth', 'prop', 'but', 'pent', 'hex', 'hept', 'oct', 'non', 'dec'];
const ID_STEM = ['met', 'et', 'prop', 'but', 'pent', 'heks', 'hept', 'okt', 'non', 'dek'];
const ID_SUF = { ane: 'ana', ene: 'ena', yne: 'una', '-1-ene': '-1-ena', anol: 'anol', anal: 'anal', 'anoic acid': 'anoat' };
const stem = n => (I18N.lang === 'id' ? ID_STEM : STEM)[n - 1];
const oName = (n, suf) => (I18N.lang === 'id' ? (suf === 'anoic acid' ? 'asam ' : '') + ID_STEM[n - 1] + ID_SUF[suf] : STEM[n - 1] + suf);   // IUPAC names (English / Indonesian)
const ALK_BP = [-161.5, -88.6, -42.1, -0.5, 36.1, 68.7, 98.4, 125.7, 150.8, 174.1];
const fml = (c, h, x = '') => `C${c > 1 ? c : ''}H${h > 1 ? h : ''}${x}`;
// condensed formula → class
const CLASSES = () => [['CH3CH2OH', T`alcohol`, T`ethanol`], ['CH3CH2CH2OH', T`alcohol`, T`propan-1-ol`], ['CH3CHO', T`aldehyde`, T`ethanal`], ['CH3CH2CHO', T`aldehyde`, T`propanal`], ['CH3COCH3', T`ketone`, T`propanone`], ['CH3COCH2CH3', T`ketone`, T`butanone`], ['CH3COOH', T`carboxylic acid`, T`ethanoic acid`], ['HCOOH', T`carboxylic acid`, T`methanoic acid`], ['CH3COOCH3', T`ester`, T`methyl ethanoate`], ['CH3COOCH2CH3', T`ester`, T`ethyl ethanoate`], ['CH3OCH3', T`ether`, T`methoxymethane`], ['CH3CH2NH2', T`amine`, T`ethylamine`], ['CH3CH2Cl', T`haloalkane`, T`chloroethane`], ['CH3CH2Br', T`haloalkane`, T`bromoethane`], ['CH2=CH2', T`alkene`, T`ethene`], ['CH3CH=CH2', T`alkene`, T`propene`]];
level({
  id: 'organic', mark: 'I', name: 'Organic Chemistry', short: 'Organic', band: 'Hydrocarbons · functional groups · reactions · polymers · life',
  color: 'lv9',
  blurb: 'The chemistry of carbon compounds: hydrocarbons and naming, functional groups, isomerism, the main organic reactions, benzene, polymers and plastics, and the molecules of life.',
  topics: [
{
  id: 'hydrocarbons', stage: 'sh', title: 'Hydrocarbons: Alkanes, Alkenes & Alkynes',
  blurb: 'Why carbon forms so many compounds, homologous series, general formulas, displayed and structural formulas, IUPAC naming, physical properties, crude oil and fractional distillation.',
  lesson: () => T`
<p>Carbon forms four covalent bonds and can bond to itself in long chains, branches and rings: that is why there are millions of organic compounds. <b>Hydrocarbons</b> contain only carbon and hydrogen.</p>
${FigRow([[dispMol(['C'], { label: T`Methane` }), T`methane $\ce{CH4}$`], [dispMol(['C', 'C'], { label: T`Ethane` }), T`ethane $\ce{C2H6}$`], [dispMol(['C', 'C', 'C'], { label: T`Propane` }), T`propane $\ce{C3H8}$`], [dispMol(['C', 'C'], { bonds: { 0: 2 }, label: T`Ethene` }), T`ethene $\ce{C2H4}$`], [dispMol(['C', 'C'], { bonds: { 0: 3 }, label: T`Ethyne` }), T`ethyne $\ce{C2H2}$`]], T`Displayed formulas show every atom and bond. Alkanes have only single bonds; alkenes have a C=C double bond; alkynes a C≡C triple bond.`)}
${Tbl([T`Series`, T`General formula`, T`Bonds`, T`Name ending`, T`Example`], [[T`alkanes`, '$\\ce{C_nH_{2n+2}}$', T`all single (saturated)`, '-ane', T`propane $\ce{C3H8}$`], [T`alkenes`, '$\\ce{C_nH_{2n}}$', T`one C=C (unsaturated)`, '-ene', T`propene $\ce{C3H6}$`], [T`alkynes`, '$\\ce{C_nH_{2n-2}}$', T`one C≡C`, '-yne', T`propyne $\ce{C3H4}$`]])}
${Key(T`<p>A <b>homologous series</b> is a family with the same general formula and functional group; each member differs from the next by $\ce{CH2}$. Their chemical properties are similar and their physical properties change gradually. <b>Naming</b> (IUPAC): the stem gives the number of carbons in the longest chain: meth (1), eth (2), prop (3), but (4), pent (5), hex (6), hept (7), oct (8), non (9), dec (10). Number the chain so the double bond or branch gets the lowest number: but-1-ene, 2-methylpropane.</p>`)}
${Fig(lineChartSvg([{ pts: ALK_BP.map((b, i) => [i + 1, b]), dots: true, cls: 'g-l1' }], { W: 420, H: 260, xMin: 0.5, xMax: 10.5, xTicks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], yMin: -180, yMax: 200, yStep: 50, xl: T`number of carbon atoms`, yl: T`boiling point (°C)`, extra: a => ln(a.X(0.5), a.Y(25), a.X(10.5), a.Y(25), 'fig-grid', ' stroke-dasharray="5 4"') + note(a.X(0.7), a.Y(25) - 5, T`room temperature`, 'start') + note(a.X(2.6), a.Y(-150), T`gases`) + note(a.X(7.2), a.Y(150), T`liquids`), label: T`Boiling points of straight-chain alkanes rise from minus 162 degrees for methane to 174 degrees for decane` }), T`Boiling points of the straight-chain alkanes (CRC Handbook). Longer molecules have more electrons and more contact, so stronger London forces: $\ce{C1}$–$\ce{C4}$ are gases at room temperature, $\ce{C5}$–$\ce{C17}$ liquids.`)}
${Key(T`<p><b>Crude oil</b> is a mixture of hydrocarbons separated by <b>fractional distillation</b> into fractions with different boiling ranges: refinery gas, petrol (gasoline), naphtha, kerosene (jet fuel), diesel, fuel oil and bitumen. Long molecules are <b>cracked</b> into shorter, more useful ones plus alkenes: $\ce{C10H22 -> C8H18 + C2H4}$.</p>`)}
${Tip(T`<p>Alkanes burn (complete combustion gives $\ce{CO2}$ + $\ce{H2O}$; with too little oxygen, poisonous CO and soot form) and react with halogens in UV light. Alkenes are much more reactive because of the C=C bond.</p>`)}`,
  gens: [
    () => { const n = ri(1, 10), k = pick([0, 1, 2].filter(t => n > 1 || t === 0)), h = [2 * n + 2, 2 * n, 2 * n - 2][k], nm = oName(n, ['ane', 'ene', 'yne'][k]); return { q: T`What is the molecular formula of ${nm}?`, a: `$\\ce{${fml(n, h)}}$`, w: [2 * n + 2, 2 * n, 2 * n - 2, 2 * n + 4].filter(x => x !== h && x > 0).slice(0, 3).map(x => `$\\ce{${fml(n, x)}}$`), only: 'mc', s: T`${stem(n)} = ${n} carbons; ${[T`alkane`, T`alkene`, T`alkyne`][k]}: $\ce{C_nH_{${['2n+2', '2n', '2n-2'][k]}}}$ → $\ce{${fml(n, h)}}$.` }; },
    () => { const n = ri(2, 8), k = pick([0, 1]), h = k ? 2 * n : 2 * n + 2, nm = oName(n, k ? 'ene' : 'ane'); return { q: T`Name the straight-chain hydrocarbon $\ce{${fml(n, h)}}$${k ? T` (double bond at the end)` : ''}.`, a: k && n > 3 ? oName(n, '-1-ene') : nm, w: [oName(n - 1, k ? 'ene' : 'ane'), oName(n, k ? 'ane' : 'ene'), oName(Math.min(10, n + 1), k ? 'ene' : 'ane')], only: 'mc', s: T`${n} carbons: ${stem(n)}-; $\ce{C_nH_{${k ? '2n' : '2n+2'}}}$ → ${k ? T`alkene` : T`alkane`}.` }; },
    () => { const [n, c] = pick([[4, 2], [5, 3], [6, 5], [7, 9]]); return { q: T`How many structural isomers does the alkane $\ce{${fml(n, 2 * n + 2)}}$ have?`, a: c, w: [c + 1, c - 1, c * 2].filter(x => x > 0 && x !== c), s: T`$\ce{C4H10}$: 2, $\ce{C5H12}$: 3, $\ce{C6H14}$: 5, $\ce{C7H16}$: 9.` }; },
    () => { const [a, b] = [...[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]].sort(() => rng() - 0.5).slice(0, 2), hi = a > b ? a : b; return { q: T`Which has the higher boiling point: ${oName(a, 'ane')} or ${oName(b, 'ane')}?`, a: oName(hi, 'ane'), w: [oName(hi === a ? b : a, 'ane'), T`they are equal`], only: 'mc', s: T`More carbons: stronger London forces. ${oName(hi, 'ane')} boils at ${NUM(ALK_BP[hi - 1])} °C.` }; },
    () => { const n = pick([3, 4, 5, 6, 7, 8]), h = 2 * n + 2, o2 = (2 * n + (n + 1)) / 2; const f = o2 % 1 ? [2, 2 * o2, 2 * n, 2 * (n + 1)] : [1, o2, n, n + 1]; return { q: T`Balance the complete combustion of $\ce{${fml(n, h)}}$: $\ce{${f[0] > 1 ? f[0] : ''}${fml(n, h)} + ? O2 -> ${f[2]}CO2 + ${f[3]}H2O}$. What is the coefficient of $\ce{O2}$?`, a: f[1], w: [f[1] + 1, f[2], f[1] * 2], s: T`O atoms on the right: $2 \times ${f[2]} + ${f[3]} = ${2 * f[2] + f[3]}$, so ${f[1]} $\ce{O2}$.` }; },
  ],
},
{
  id: 'functional-groups', stage: 'sh', title: 'Functional Groups & Naming',
  blurb: 'Functional groups (alcohols, haloalkanes, aldehydes, ketones, carboxylic acids, esters, ethers, amines, amides), naming them, and how they affect properties.',
  lesson: () => T`
<p>A <b>functional group</b> is the atom or group of atoms that gives a family of compounds its characteristic reactions. The rest of the molecule is mostly a hydrocarbon "skeleton".</p>
${FigRow([[dispMol(['C', 'C'], { subs: [[1, 'right', 'OH']], label: T`Ethanol` }), T`alcohol: ethanol`], [dispMol(['C', 'C'], { subs: [[1, 'up', 'O', 2], [1, 'right', 'H']], label: T`Ethanal` }), T`aldehyde: ethanal`], [dispMol(['C', 'C', 'C'], { subs: [[1, 'up', 'O', 2]], label: T`Propanone` }), T`ketone: propanone`], [dispMol(['C', 'C'], { subs: [[1, 'up', 'O', 2], [1, 'right', 'OH']], label: T`Ethanoic acid` }), T`carboxylic acid: ethanoic acid`], [dispMol(['C', 'C', 'O', 'C'], { subs: [[1, 'up', 'O', 2]], label: T`Methyl ethanoate` }), T`ester: methyl ethanoate`], [dispMol(['C', 'C'], { subs: [[1, 'right', 'NH₂']], label: T`Ethylamine` }), T`amine: ethylamine`]], T`Common functional groups, each shown on a small molecule.`)}
${Tbl([T`Family`, T`Group`, T`Suffix / prefix`, T`Example`], [[T`alcohol`, '–OH', '-ol', T`ethanol $\ce{C2H5OH}$`], [T`haloalkane`, '–F, –Cl, –Br, –I', T`fluoro-, chloro-, bromo-, iodo-`, T`chloromethane $\ce{CH3Cl}$`], [T`aldehyde`, '–CHO', '-al', T`ethanal $\ce{CH3CHO}$`], [T`ketone`, 'C–CO–C', '-one', T`propanone $\ce{CH3COCH3}$`], [T`carboxylic acid`, '–COOH', T`-oic acid`, T`ethanoic acid $\ce{CH3COOH}$`], [T`ester`, '–COO–', T`alkyl -oate`, T`ethyl ethanoate $\ce{CH3COOC2H5}$`], [T`ether`, 'C–O–C', T`alkoxy-`, T`methoxymethane $\ce{CH3OCH3}$`], [T`amine`, '–NH₂', T`-amine`, T`ethylamine $\ce{C2H5NH2}$`], [T`amide`, '–CONH₂', '-amide', T`ethanamide $\ce{CH3CONH2}$`]])}
${Key(T`<p>Groups that can form hydrogen bonds (–OH, –COOH, –NH₂) raise boiling points and water solubility: ethanol ($M_r$ 46) boils at 78 °C, propane ($M_r$ 44) at −42 °C. Solubility falls as the hydrocarbon chain gets longer. Carboxylic acids are weak acids; amines are weak bases.</p>`)}
${Tip(T`<p>Esters have fruity smells (pentyl ethanoate smells of bananas, octyl ethanoate of oranges) and are used in flavourings and perfumes. Methanal (formaldehyde) preserves specimens; propanone (acetone) is nail-varnish remover.</p>`)}`,
  gens: [
    () => { const all = CLASSES(), [f, c] = pick(all); return { q: T`To which family does $\ce{${f}}$ belong?`, a: c, w: [...new Set(all.map(x => x[1]))].filter(x => x !== c).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`Its functional group makes it an <b>${c}</b>.` }; },
    () => { const all = CLASSES(), [f, , n] = pick(all); return { q: T`What is the IUPAC name of $\ce{${f}}$?`, a: n, w: all.filter(x => x[2] !== n).sort(() => rng() - 0.5).slice(0, 3).map(x => x[2]), only: 'mc', s: T`<b>${n}</b>.` }; },
    () => { const n = ri(1, 6), k = pick(['ol', 'oic', 'al']), nm = oName(n, k === 'ol' ? 'anol' : k === 'al' ? 'anal' : 'anoic acid'), f = k === 'ol' ? `${fml(n, 2 * n + 1)}OH` : k === 'al' ? (n === 1 ? 'HCHO' : `${fml(n - 1, 2 * n - 1)}CHO`) : (n === 1 ? 'HCOOH' : `${fml(n - 1, 2 * n - 1)}COOH`); return { q: T`What is the formula of ${nm}?`, a: `$\\ce{${f}}$`, w: [`$\\ce{${fml(n, 2 * n + 2)}}$`, `$\\ce{${fml(n + 1, 2 * n + 3)}OH}$`, `$\\ce{${fml(n, 2 * n)}O2}$` === `$\\ce{${f}}$` ? `$\\ce{${fml(n, 2 * n + 2)}O}$` : `$\\ce{${fml(n, 2 * n)}O2}$`].filter(x => x !== `$\\ce{${f}}$`), only: 'mc', s: T`${stem(n)}- = ${n} carbon${n > 1 ? 's' : ''}: $\ce{${f}}$.` }; },
    () => { const [a, b, hi] = pick([[T`ethanol`, T`propane`, 0], [T`ethanoic acid`, T`ethanal`, 0], [T`butan-1-ol`, T`pentane`, 0], [T`methoxymethane`, T`ethanol`, 1], [T`propanone`, T`propan-1-ol`, 1]]); return { q: T`Which has the higher boiling point: ${a} or ${b}?`, a: hi ? b : a, w: [hi ? a : b, T`they are equal`], only: 'mc', s: T`${hi ? b : a} can form hydrogen bonds between its molecules (–OH).` }; },
    () => { const [acid, alc, est] = pick([[T`ethanoic acid`, T`methanol`, T`methyl ethanoate`], [T`ethanoic acid`, T`ethanol`, T`ethyl ethanoate`], [T`methanoic acid`, T`ethanol`, T`ethyl methanoate`], [T`propanoic acid`, T`methanol`, T`methyl propanoate`], [T`butanoic acid`, T`ethanol`, T`ethyl butanoate`]]); return { q: T`Which ester forms from ${acid} and ${alc}?`, a: est, w: [T`methyl ethanoate`, T`ethyl ethanoate`, T`ethyl methanoate`, T`methyl propanoate`, T`ethyl butanoate`, T`propyl methanoate`].filter(x => x !== est).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`The alcohol gives the first word (alkyl), the acid the second (-oate): <b>${est}</b>.` }; },
  ],
},
{
  id: 'isomerism', stage: 'sh', title: 'Isomerism',
  blurb: 'Structural isomers (chain, position, functional group) and stereoisomers: cis/trans (E/Z) isomers of alkenes and optical isomers with a chiral carbon.',
  lesson: () => T`
<p><b>Isomers</b> have the same molecular formula but a different arrangement of atoms. They can have quite different properties.</p>
${FigRow([[dispMol(['C', 'C', 'C', 'C'], { label: T`Butane` }), T`butane (b.p. −0.5 °C)`], [dispMol(['C', 'C', 'C'], { subs: [[1, 'down', 'CH₃']], label: T`Methylpropane` }), T`2-methylpropane (b.p. −11.7 °C)`]], T`Chain isomers of $\ce{C4H10}$. The branched isomer is more compact, has less surface contact and therefore a lower boiling point.`)}
${Tbl([T`Type`, T`What differs`, T`Example`], [[T`chain`, T`the carbon skeleton (branching)`, T`butane / 2-methylpropane`], [T`position`, T`the position of the functional group`, T`propan-1-ol / propan-2-ol`], [T`functional group`, T`the functional group itself`, T`ethanol / methoxymethane ($\ce{C2H6O}$); propanal / propanone`]])}
<h3>Stereoisomers</h3>
${FigRow([[molSvg([['C', 0, 0], ['C', 1.3, 0], ['H₃C', -0.9, -0.8], ['H', -0.8, 0.8], ['CH₃', 2.2, -0.8], ['H', 2.1, 0.8]], [[0, 1, 2], [0, 2], [0, 3], [1, 4], [1, 5]], { u: 46, label: T`cis-but-2-ene: both methyl groups on the same side` }), T`cis (Z): same side`], [molSvg([['C', 0, 0], ['C', 1.3, 0], ['H₃C', -0.9, -0.8], ['H', -0.8, 0.8], ['H', 2.1, -0.8], ['CH₃', 2.2, 0.8]], [[0, 1, 2], [0, 2], [0, 3], [1, 4], [1, 5]], { u: 46, label: T`trans-but-2-ene: the methyl groups on opposite sides` }), T`trans (E): opposite sides`]], T`The C=C bond cannot rotate, so but-2-ene exists as two <b>cis/trans</b> (geometric) isomers. This needs two different groups on each carbon of the double bond.`)}
${Key(T`<p>A carbon atom bonded to four <b>different</b> groups is <b>chiral</b>. Its two mirror-image forms cannot be superimposed, like left and right hands: they are <b>optical isomers</b> (enantiomers). They rotate plane-polarised light in opposite directions and can act very differently in the body: one form of carvone smells of spearmint, the other of caraway.</p>`)}
${FigRow([[shapeSvg('tetrahedral', { centre: 'C', outer: 'X', W: 170, H: 170, label: T`A chiral carbon with four different groups` }).replace(/class="ch-bX"/g, (m, i) => m).replace(/(<circle[^>]*class=")ch-bX(")/, '$1ch-bO$2').replace(/(<circle[^>]*class=")ch-bX(")/, '$1ch-bN$2').replace(/(<circle[^>]*class=")ch-bX(")/, '$1ch-bS$2'), T`one enantiomer`], [shapeSvg('tetrahedral', { centre: 'C', outer: 'X', W: 170, H: 170, label: T`Its mirror image` }).replace(/(<circle[^>]*class=")ch-bX(")/, '$1ch-bO$2').replace(/(<circle[^>]*class=")ch-bX(")/, '$1ch-bN$2').replace(/(<circle[^>]*class=")ch-bX(")/, '$1ch-bS$2').replace('<svg ', '<svg style="transform:scaleX(-1)" '), T`its mirror image`]], T`Four different groups (four colours) around a carbon: the molecule and its mirror image are not the same, however you turn them.`)}
${Tip(T`<p>Thalidomide (1950s–60s) is the famous warning: one enantiomer eased morning sickness, the other caused birth defects. Drug makers now test each enantiomer separately.</p>`)}`,
  gens: [
    () => { const [a, b, t] = pick([[T`butane`, T`2-methylpropane`, 0], [T`pentane`, T`2,2-dimethylpropane`, 0], [T`propan-1-ol`, T`propan-2-ol`, 1], [T`but-1-ene`, T`but-2-ene`, 1], [T`ethanol`, T`methoxymethane`, 2], [T`propanal`, T`propanone`, 2], [T`cis-but-2-ene`, T`trans-but-2-ene`, 3]]), N = [T`chain isomers`, T`position isomers`, T`functional group isomers`, T`cis/trans isomers`]; return { q: T`What kind of isomers are ${a} and ${b}?`, a: N[t], w: N.filter((_, i) => i !== t), only: 'mc', s: T`<b>${N[t]}</b>.` }; },
    () => { const [m, y] = pick([[T`but-2-ene (CH₃CH=CHCH₃)`, true], [T`propene (CH₂=CHCH₃)`, false], [T`but-1-ene (CH₂=CHCH₂CH₃)`, false], [T`pent-2-ene`, true], [T`1,2-dichloroethene (CHCl=CHCl)`, true], [T`1,1-dichloroethene (CCl₂=CH₂)`, false]]); return { q: T`Can ${m} show cis/trans isomerism?`, a: y ? T`yes` : T`no`, w: [y ? T`no` : T`yes`], only: 'mc', s: y ? T`Each carbon of C=C has two different groups: <b>yes</b>.` : T`One carbon of C=C carries two identical groups: <b>no</b>.` }; },
    () => { const [m, y] = pick([[T`butan-2-ol CH₃CH(OH)CH₂CH₃`, true], [T`propan-2-ol CH₃CH(OH)CH₃`, false], [T`2-chlorobutane CH₃CHClCH₂CH₃`, true], [T`lactic acid CH₃CH(OH)COOH`, true], [T`ethanol CH₃CH₂OH`, false], [T`alanine CH₃CH(NH₂)COOH`, true], [T`glycine H₂NCH₂COOH`, false]]); return { q: T`Does ${m} have a chiral carbon?`, a: y ? T`yes` : T`no`, w: [y ? T`no` : T`yes`], only: 'mc', s: y ? T`One carbon carries four different groups: <b>yes</b>, it has optical isomers.` : T`No carbon carries four different groups: <b>no</b>.` }; },
    () => { const [f, n] = pick([['C4H10', 2], ['C5H12', 3], ['C3H7Cl', 2], ['C2H6O', 2], ['C3H8O', 3], ['C4H8 (alkenes, structural)', 3]]); return { q: T`How many structural isomers have the formula $\ce{${f.split(' ')[0]}}$${f.includes(' ') ? T` (counting only open-chain alkenes, not stereoisomers)` : ''}?`, a: n, w: [n + 1, n - 1, n + 2].filter(x => x > 0), s: T`<b>${n}</b>.` }; },
  ],
},
{
  id: 'organic-reactions', stage: 'sh', title: 'Organic Reactions',
  blurb: 'Combustion, substitution of alkanes, addition to alkenes (bromine test, hydrogenation, hydration), elimination, oxidation of alcohols, esterification, and reaction pathways.',
  lesson: () => T`
${Tbl([T`Reaction type`, T`What happens`, T`Example`], [[T`substitution`, T`one atom or group replaces another`, '$\\ce{CH4 + Cl2 ->[UV] CH3Cl + HCl}$'], [T`addition`, T`two molecules join to make one; C=C opens up`, '$\\ce{C2H4 + Br2 -> C2H4Br2}$'], [T`elimination`, T`a small molecule is removed and a C=C forms`, '$\\ce{C2H5OH ->[H2SO4][170\\,°C] C2H4 + H2O}$'], [T`oxidation`, T`gain of O or loss of H`, '$\\ce{C2H5OH ->[K2Cr2O7/H+] CH3COOH}$'], [T`condensation`, T`two molecules join and lose a small molecule`, '$\\ce{CH3COOH + C2H5OH <=> CH3COOC2H5 + H2O}$']])}
${Key(T`<p><b>Test for C=C:</b> shake with orange-brown bromine water. An alkene decolourises it quickly (addition); an alkane does not (without UV light).</p>`)}
${Fig((() => { let k = 0; const cols = [['#d2691e', 0.8], ['#d2691e', 0.12], ['#d2691e', 0.8]]; return apparatusSvg([['tube', T`before: orange-brown`], ['tube', T`alkene added: colourless`], ['tube', T`alkane added: stays orange`]], { label: T`Bromine water test: orange-brown before, colourless with an alkene, still orange with an alkane` }).replace(/class="ch-liq"/g, () => { const [c, o] = cols[k++]; return `class="ch-liq" style="fill:${c};opacity:${o}"`; }); })(), T`The bromine water test.`)}
<h3>Addition reactions of alkenes</h3>
${Tbl([T`Reagent`, T`Conditions`, T`Product (from ethene)`], [['$\\ce{H2}$', T`Ni catalyst, 150 °C (hydrogenation, used to harden vegetable oils)`, T`ethane`], ['$\\ce{Br2}$ / $\\ce{Cl2}$', T`room temperature`, T`1,2-dibromoethane`], ['$\\ce{HBr}$', T`room temperature`, T`bromoethane`], ['$\\ce{H2O}$ (steam)', T`$\ce{H3PO4}$ catalyst, 300 °C, 60 atm (hydration)`, T`ethanol`]])}
<h3>A reaction pathway</h3>
${Fig(flowSvg([T`ethene CH₂=CH₂`, T`+ H₂O (steam, H₃PO₄) → ethanol C₂H₅OH`, T`oxidise (K₂Cr₂O₇/H⁺, distil) → ethanal CH₃CHO`, T`oxidise (reflux) → ethanoic acid CH₃COOH`, T`+ ethanol (conc. H₂SO₄) → ethyl ethanoate`], { W: 440, label: T`A reaction pathway from ethene to ethanol, ethanal, ethanoic acid and ethyl ethanoate` }), T`Linking the functional groups. Primary alcohols oxidise to aldehydes, then carboxylic acids; secondary alcohols to ketones; tertiary alcohols resist oxidation. Acidified dichromate turns from orange to green when it oxidises an alcohol.`)}
${Tip(T`<p>Ethanol for fuel and drinks is also made by <b>fermentation</b> of sugars with yeast: $\ce{C6H12O6 -> 2C2H5OH + 2CO2}$ at about 35 °C without air.</p>`)}`,
  gens: [
    () => { const [e, t] = pick([['\\ce{CH4 + Cl2 -> CH3Cl + HCl}', 0], ['\\ce{C2H6 + Br2 -> C2H5Br + HBr}', 0], ['\\ce{C2H4 + H2 -> C2H6}', 1], ['\\ce{C2H4 + HBr -> C2H5Br}', 1], ['\\ce{C2H4 + H2O -> C2H5OH}', 1], ['\\ce{C2H5OH -> C2H4 + H2O}', 2], ['\\ce{C2H5Br + KOH -> C2H4 + KBr + H2O}', 2], ['\\ce{CH3COOH + CH3OH -> CH3COOCH3 + H2O}', 3]]), N = [T`substitution`, T`addition`, T`elimination`, T`condensation (esterification)`]; return { q: T`What type of reaction is $${e}$?`, a: N[t], w: N.filter((_, i) => i !== t), only: 'mc', s: T`<b>${N[t]}</b>.` }; },
    () => { const [r, p] = pick([[T`ethene + hydrogen (Ni)`, T`ethane`], [T`ethene + bromine`, T`1,2-dibromoethane`], [T`ethene + steam (H₃PO₄)`, T`ethanol`], [T`ethene + hydrogen bromide`, T`bromoethane`], [T`propene + hydrogen (Ni)`, T`propane`]]); return { q: T`What is the product of ${r}?`, a: p, w: [T`ethane`, T`1,2-dibromoethane`, T`ethanol`, T`bromoethane`, T`propane`, T`ethanoic acid`].filter(x => x !== p).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`Addition across C=C: <b>${p}</b>.` }; },
    () => { const [a, t, p] = pick([[T`ethanol`, 0, T`ethanal, then ethanoic acid`], [T`propan-1-ol`, 0, T`propanal, then propanoic acid`], [T`propan-2-ol`, 1, T`propanone`], [T`butan-2-ol`, 1, T`butanone`], [T`2-methylpropan-2-ol`, 2, T`no reaction`]]); return { q: T`What does ${a} give when warmed with acidified potassium dichromate?`, a: p, w: [T`ethanal, then ethanoic acid`, T`propanone`, T`no reaction`, T`an alkene`].filter(x => x !== p).slice(0, 3), only: 'mc', s: [T`A primary alcohol`, T`A secondary alcohol`, T`A tertiary alcohol`][t] + T`: <b>${p}</b>.` }; },
    () => { const [x, a] = pick([[T`hexene`, T`it decolourises quickly`], [T`hexane`, T`it stays orange-brown`], [T`cyclohexene`, T`it decolourises quickly`], [T`octane`, T`it stays orange-brown`]]); return { q: T`What happens when ${x} is shaken with bromine water?`, a, w: [a === T`it decolourises quickly` ? T`it stays orange-brown` : T`it decolourises quickly`, T`it turns blue`], only: 'mc', s: a === T`it decolourises quickly` ? T`It has a C=C bond, which adds bromine.` : T`Saturated: no addition reaction.` }; },
  ],
},
{
  id: 'benzene', stage: 'sh', title: 'Benzene & Aromatic Compounds',
  blurb: 'The structure of benzene (Kekulé and the delocalised model), its stability, electrophilic substitution (nitration, halogenation, Friedel–Crafts), and important aromatic compounds.',
  lesson: () => T`
<p><b>Benzene</b> $\ce{C6H6}$ is a flat ring of six carbon atoms. In 1865 August Kekulé proposed alternating single and double bonds. But all six C–C bonds in benzene are the same length (0.140 nm, between C–C 0.154 nm and C=C 0.134 nm), and benzene does not decolourise bromine water.</p>
${Fig(benzeneSvg({ names: [T`Kekulé structures`, T`delocalised model`], label: T`Two Kekulé structures of benzene with alternating double bonds, and the modern ring with a circle showing delocalised electrons` }), T`Each carbon uses three electrons for σ bonds and gives its fourth to a ring of six <b>delocalised</b> electrons above and below the plane, drawn as a circle.`)}
${Key(T`<p>Delocalisation makes benzene about 150 kJ/mol more stable than a "cyclohexatriene" would be. So benzene prefers <b>substitution</b>, which keeps the ring intact, to addition. An electrophile (electron-pair acceptor) attacks the electron-rich ring:</p>`)}
${Tbl([T`Reaction`, T`Reagents`, T`Product`], [[T`nitration`, T`conc. $\ce{HNO3}$ + conc. $\ce{H2SO4}$, 50 °C`, T`nitrobenzene $\ce{C6H5NO2}$`], [T`halogenation`, T`$\ce{Br2}$ with $\ce{FeBr3}$ catalyst`, T`bromobenzene $\ce{C6H5Br}$`], [T`Friedel–Crafts alkylation`, T`$\ce{CH3Cl}$ with $\ce{AlCl3}$`, T`methylbenzene (toluene)`], [T`Friedel–Crafts acylation`, T`$\ce{CH3COCl}$ with $\ce{AlCl3}$`, T`phenylethanone`]])}
${FigRow([['phenol', 'OH'], ['methylbenzene', 'CH₃'], ['benzoic acid', 'COOH'], ['aniline', 'NH₂']].map(([n, g]) => [benzeneSvg({ names: ['', ''], label: n }).replace(/viewBox="0 0 460 170" style="max-width:\d+px"/, 'viewBox="320 -6 130 146" style="max-width:150px"').replace('</svg>', sL(380, 28, 380, 16, 'ch-bond') + sT(380, 12, g, `ch-at ${atomCls(g)}`, 'middle', ' style="font-size:12px"') + '</svg>'), T`${n}`]), T`Some important aromatic compounds: phenol (disinfectants, resins), methylbenzene (solvent), benzoic acid (food preservative E210), aniline (dyes).`)}
${Tip(T`<p>Benzene itself is carcinogenic, so methylbenzene is used as a solvent instead. Aromatic rings occur widely in nature and medicines: aspirin, paracetamol, amino acids such as phenylalanine, and DNA bases.</p>`)}`,
  gens: [
    () => pick([
      { q: T`Why does benzene not decolourise bromine water like alkenes do?`, a: T`Its delocalised electrons make it stable; addition would destroy this`, w: [T`It has no double bonds or electrons between carbons`, T`It is a saturated alkane`, T`Bromine is not an electrophile`], only: 'mc', s: T`Benzene prefers substitution, keeping the delocalised ring.` },
      { q: T`All C–C bonds in benzene are 0.140 nm long. What does this show?`, a: T`The electrons are delocalised; there are no separate single and double bonds`, w: [T`Benzene has three double bonds`, T`Benzene is not a ring`, T`Benzene has only single bonds`], only: 'mc', s: T`Between single (0.154 nm) and double (0.134 nm).` },
      { q: T`What type of reaction does benzene mainly undergo?`, a: T`electrophilic substitution`, w: [T`electrophilic addition`, T`elimination`, T`nucleophilic addition`], only: 'mc', s: T`An electrophile replaces an H atom on the ring.` },
      { q: T`How many delocalised electrons are in a benzene ring?`, a: '6', w: ['3', '12', '2'], only: 'mc', s: T`One from each of the six carbon atoms.` },
    ]),
    () => { const [r, p] = pick([[T`concentrated nitric and sulfuric acid at 50 °C`, T`nitrobenzene`], [T`bromine with an FeBr₃ catalyst`, T`bromobenzene`], [T`chloromethane with an AlCl₃ catalyst`, T`methylbenzene`], [T`ethanoyl chloride with an AlCl₃ catalyst`, T`phenylethanone`]]); return { q: T`Benzene reacts with ${r}. What is the organic product?`, a: p, w: [T`nitrobenzene`, T`bromobenzene`, T`methylbenzene`, T`phenylethanone`, T`cyclohexane`].filter(x => x !== p).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`<b>${p}</b>.` }; },
    () => { const [g, n] = pick([['OH', T`phenol`], ['CH₃', T`methylbenzene`], ['COOH', T`benzoic acid`], ['NH₂', T`phenylamine (aniline)`], ['NO₂', T`nitrobenzene`], ['Cl', T`chlorobenzene`]]); return { q: T`What is the name of C₆H₅–${g}?`, a: n, w: [T`phenol`, T`methylbenzene`, T`benzoic acid`, T`phenylamine (aniline)`, T`nitrobenzene`, T`chlorobenzene`].filter(x => x !== n).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`<b>${n}</b>.` }; },
  ],
},
{
  id: 'polymers', stage: 'sh', title: 'Polymers & Plastics',
  blurb: 'Addition polymers from alkenes, repeat units, condensation polymers (polyesters, polyamides), natural polymers, properties and uses of plastics, and the problems of plastic waste and recycling.',
  lesson: () => T`
<p><b>Polymers</b> are very long molecules made by joining thousands of small molecules called <b>monomers</b>.</p>
${Fig(polymerSvg({ names: [T`polymerisation`, T`ethene (monomer)`, T`poly(ethene): repeat unit`], label: T`Many ethene molecules join into poly(ethene); the repeat unit is shown in brackets with n` }), T`<b>Addition polymerisation:</b> the C=C bonds open and the monomers link into a chain; nothing else is formed. The repeat unit is written in brackets with $n$ (often several thousand).`)}
${Tbl([T`Monomer`, T`Polymer`, T`Uses`], [[T`ethene $\ce{CH2=CH2}$`, T`poly(ethene), PE`, T`bags, bottles, film`], [T`propene $\ce{CH2=CHCH3}$`, T`poly(propene), PP`, T`crates, ropes, food tubs`], [T`chloroethene $\ce{CH2=CHCl}$`, T`poly(chloroethene), PVC`, T`pipes, window frames, cable insulation`], [T`phenylethene $\ce{CH2=CHC6H5}$`, T`poly(phenylethene), PS`, T`packaging foam, cups`], [T`tetrafluoroethene $\ce{CF2=CF2}$`, T`PTFE (Teflon)`, T`non-stick pans`]])}
${Key(T`<p><b>Condensation polymers</b> form when monomers with two functional groups join and lose a small molecule (usually water) at each link. A diacid + a diol gives a <b>polyester</b> (PET for bottles and fibres); a diacid + a diamine gives a <b>polyamide</b> (nylon, Kevlar). Proteins (from amino acids), starch and cellulose (from glucose) and DNA are natural condensation polymers.</p>`)}
${Fig(barChartSvg([{ label: T`packaging`, value: 36 }, { label: T`building`, value: 16 }, { label: T`textiles`, value: 14 }, { label: T`consumer`, value: 10 }, { label: T`transport`, value: 7 }, { label: T`electrical`, value: 4 }, { label: T`other`, value: 13 }].map((x, i) => ({ ...x, show: x.value + '%', cls: 'g-s' + ((i % 6) + 1) })), { W: 540, H: 250, yMax: 40, yStep: 10, yl: T`share of plastic use (%)`, label: T`World plastic use by sector: packaging 36 percent is the largest` }), T`How the world uses plastic (UNEP, <i>Single-use plastics</i>, 2018). Packaging, much of it used only once, is the largest share.`)}
${Tip(T`<p>Most addition polymers are not biodegradable: they persist for centuries and break into microplastics. Solutions: reduce and reuse, mechanical recycling (the resin codes 1–7 on products tell them apart), chemical recycling, and biodegradable polymers such as PLA made from corn starch.</p>`)}`,
  gens: [
    () => { const [m, p] = pick([[T`ethene`, T`poly(ethene)`], [T`propene`, T`poly(propene)`], [T`chloroethene`, T`poly(chloroethene) (PVC)`], [T`phenylethene`, T`poly(phenylethene) (polystyrene)`], [T`tetrafluoroethene`, T`PTFE`]]); return { q: T`Which polymer is made from ${m}?`, a: p, w: [T`poly(ethene)`, T`poly(propene)`, T`poly(chloroethene) (PVC)`, T`poly(phenylethene) (polystyrene)`, T`PTFE`, T`nylon`].filter(x => x !== p).sort(() => rng() - 0.5).slice(0, 3), only: 'mc', s: T`Addition polymerisation of ${m}: <b>${p}</b>.` }; },
    () => { const [p, t] = pick([[T`poly(ethene)`, 0], [T`PVC`, 0], [T`polystyrene`, 0], [T`nylon`, 1], [T`PET (polyester)`, 1], [T`protein`, 1], [T`starch`, 1], [T`PTFE`, 0]]), N = [T`addition polymer`, T`condensation polymer`]; return { q: T`Is ${p} an addition or a condensation polymer?`, a: N[t], w: [N[1 - t]], only: 'mc', s: t ? T`Its links form with loss of a small molecule (water): <b>condensation</b>.` : T`Made from an alkene monomer with no by-product: <b>addition</b>.` }; },
    () => { const n = pick([1000, 2000, 5000, 10000]), [m, Mm] = pick([[T`ethene`, 28], [T`propene`, 42], [T`chloroethene`, 62.5], [T`tetrafluoroethene`, 100]]), Mr = n * Mm; return { q: T`A chain of poly(${m}) is made from ${NUM(n)} monomers ($M_r$ of monomer = ${NUM(Mm)}). What is its relative molecular mass?`, a: Mr, rtol: 0.001, w: [Mr / 2, Mr * 2, n + Mm], s: T`Addition polymers keep every atom: $${M(n)} \times ${M(Mm)} = ${M(Mr)}$.` }; },
    () => pick([
      { q: T`What small molecule is usually released when a condensation polymer forms?`, a: T`water`, w: [T`carbon dioxide`, T`hydrogen`, T`oxygen`], only: 'mc', s: T`Each new ester or amide link releases $\ce{H2O}$ (sometimes HCl).` },
      { q: T`Why are most plastics a waste problem?`, a: T`They are not biodegradable and persist for a very long time`, w: [T`They dissolve in water`, T`They are too heavy`, T`They are made from metals`], only: 'mc', s: T`Bacteria cannot break down their long C–C chains.` },
    ]),
  ],
},
{
  id: 'biomolecules', stage: 'sh', title: 'Molecules of Life',
  blurb: 'Carbohydrates (glucose, disaccharides, starch, cellulose), lipids (fats and oils), proteins (amino acids, peptide bonds, structure, enzymes) and nucleic acids.',
  lesson: () => T`
<p>Living things are built from four families of organic molecules. Three of them are polymers made by condensation.</p>
${FigRow([[glucoseSvg({ label: T`Ring structure of alpha glucose` }), T`α-glucose ($\ce{C6H12O6}$), ring form`]], T`Glucose is the main fuel of cells: $\ce{C6H12O6 + 6O2 -> 6CO2 + 6H2O}$, $\Delta H = -2803$ kJ/mol (respiration). In water it exists mostly as this six-membered ring.`)}
${Tbl([T`Carbohydrate`, T`Made of`, T`Role`], [[T`glucose, fructose`, T`monosaccharides`, T`energy`], [T`sucrose (table sugar)`, T`glucose + fructose`, T`transport in plants, sweetener`], [T`lactose`, T`glucose + galactose`, T`milk sugar`], [T`starch, glycogen`, T`many α-glucose`, T`energy store in plants / animals`], [T`cellulose`, T`many β-glucose`, T`plant cell walls, fibre`]])}
${Key(T`<p><b>Proteins</b> are polymers of <b>amino acids</b>, $\ce{H2N-CHR-COOH}$, joined by <b>peptide (amide) bonds</b> –CO–NH–. The 20 amino acids differ in the side chain R. The sequence (primary structure) folds into helices and sheets (secondary), then into a 3-D shape (tertiary). <b>Enzymes</b> are proteins that catalyse reactions; heat or extreme pH <b>denatures</b> them by destroying the shape.</p>`)}
${Fig(`<svg viewBox="0 0 530 130" style="max-width:690px" role="img" aria-label="${T`Two amino acids join with loss of water to form a peptide bond`}">` + sT(60, 60, 'H₂N–CH–COOH', 'mf-lab-b') + sT(60, 86, 'R₁', 'mf-small') + sT(128, 64, '+', 'mf-lab-b') + sT(195, 60, 'H₂N–CH–COOH', 'mf-lab-b') + sT(195, 86, 'R₂', 'mf-small') + sArrow(252, 56, 290, 56, 'mf-line', 8) + sT(410, 60, 'H₂N–CH–CO–NH–CH–COOH', 'mf-lab-b') + sT(370, 86, 'R₁', 'mf-small') + sT(437, 86, 'R₂', 'mf-small') + sR(377, 42, 52, 26, '', 5, ' style="fill:none;stroke:var(--lv4);stroke-width:2"') + sT(417, 112, T`peptide bond`, 'mf-small') + sT(271, 44, '−H₂O', 'mf-small') + '</svg>', T`Two amino acids make a dipeptide by condensation; the new –CO–NH– group is the peptide bond.`)}
${Key(T`<p><b>Lipids</b> (fats and oils) are esters of glycerol (propane-1,2,3-triol) with three fatty acids: <b>triglycerides</b>. Saturated fats (mostly animal) are solid; unsaturated oils (C=C bonds, mostly plant) are liquid. <b>Nucleic acids</b> (DNA, RNA) are polymers of nucleotides (sugar + phosphate + base) and store genetic information.</p>`)}
${Tbl([T`Test`, T`For`, T`Positive result`], [[T`iodine solution`, T`starch`, T`orange → blue-black`], [T`Benedict's (or Fehling's) solution, heat`, T`reducing sugars (glucose)`, T`blue → brick-red precipitate`], [T`biuret reagent`, T`protein (peptide bonds)`, T`blue → purple`], [T`ethanol emulsion`, T`lipids`, T`cloudy white emulsion`]])}
${Tip(T`<p>Daily energy values on food labels: carbohydrate and protein about 17 kJ/g, fat about 37 kJ/g, which is why fat is the body's compact energy store.</p>`)}`,
  gens: [
    () => { const [x, t] = pick([[T`starch`, T`iodine solution: blue-black`], [T`glucose`, T`Benedict's solution: brick-red precipitate`], [T`egg white (protein)`, T`biuret reagent: purple`], [T`vegetable oil`, T`ethanol emulsion: cloudy white`]]); return { q: T`Which test gives a positive result for ${x}?`, a: t, w: [T`iodine solution: blue-black`, T`Benedict's solution: brick-red precipitate`, T`biuret reagent: purple`, T`ethanol emulsion: cloudy white`].filter(z => z !== t), only: 'mc', s: T`<b>${t}</b>.` }; },
    () => { const [p, m] = pick([[T`starch`, T`glucose`], [T`cellulose`, T`glucose`], [T`protein`, T`amino acids`], [T`DNA`, T`nucleotides`], [T`glycogen`, T`glucose`]]); return { q: T`What are the monomers of ${p}?`, a: m, w: [T`glucose`, T`amino acids`, T`nucleotides`, T`fatty acids`].filter(z => z !== m), only: 'mc', s: T`<b>${m}</b>.` }; },
    () => { const n = pick([2, 3, 5, 10, 50]); return { q: T`How many water molecules are released when ${n} amino acids join into one chain?`, a: n - 1, w: [n, n + 1, 2 * n], s: T`One water per peptide bond; a chain of ${n} has ${n - 1} bonds.` }; },
    () => pick([
      { q: T`Which bond links amino acids in a protein?`, a: T`the peptide (amide) bond`, w: [T`the ester bond`, T`the glycosidic bond`, T`the hydrogen bond`], only: 'mc', s: T`–CO–NH–.` },
      { q: T`Why are most plant oils liquid while animal fats are solid?`, a: T`Oils contain C=C double bonds that kink the chains`, w: [T`Oils have longer chains`, T`Fats contain water`, T`Oils are not esters`], only: 'mc', s: T`Kinked unsaturated chains cannot pack closely, so the forces between them are weaker.` },
      { q: T`What happens to an enzyme when it is heated strongly?`, a: T`It is denatured: its shape changes and it stops working`, w: [T`It works faster forever`, T`It turns into glucose`, T`Nothing`], only: 'mc', s: T`The 3-D shape of the active site is lost.` },
    ]),
  ],
},
  ],
});
})();
